### ISSUE TITLE
Allow clicking on #channel in /mentions to open the channel's tab

### ISSUE THREAD

**Issue by terrabuck** [Chatterino/chatterino2#1126]
I'd like to be able to click on the #channel that appears on the left of each message within /mentions and have that open up the existing tab of that channel or if no existing tab open that channel in a new tab. Thank you very much 👍 

![image](https://user-images.githubusercontent.com/29488729/60759578-7168ac80-9ff5-11e9-8a0c-d7d9cae3ab5c.png)

**Comment by TranRed** [comment]
What should open if you have this channel in multiple splits? First one?

**Comment by terrabuck** [comment]
Yea, first instance I suppose

**Comment by Felanbird** [comment]
An option to force open the channel in a new tab could also be useful b/c I personally have tab with 25~ channels in it for pings and I just open a new window to respond and close it later.

niche addition tho.

**Comment by nitrousGranola** [comment]
Would also be nice if it pulsed a highlight around the split shortly when you clicked, either when it's in the same or different tab as /mentions. Tabbing into that split's text box would be a nice addition.

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.

**Comment by zneix** [comment]
@terrabuck to your (and my) surprise, this feature isn't out of scope of the Chatterino project as it was actually merged in in #2220 and is available in nightly since November. However, it doesn't open a new split if your currently open splits don't have the tab on which you're clicking. I see @Felanbird also requested this, so should opening new tab be added as well?
