### ISSUE TITLE
Connecting or Disconnecting a VPN requires a manual reconnect

### ISSUE THREAD

**Issue by Chronophylos** [Chatterino/chatterino2#1164]
Maybe chatterino can detect this and reconnect automatically

**Comment by pajlada** [comment]
I haven't had this happen to me on Linux, but my VPN connections don't try to take over the chat stream so maybe that's why

**Comment by Chronophylos** [comment]
I noticed streams get disconnected as well. Maybe this is a issue with nordvpn.

**Comment by SLCH** [comment]
Usually not an issue with OpenVPN - ch2 autoreconnects.
Although it did happen like twice during last 2 years of using ch2.

**Comment by hemirt** [comment]
I'm using OpenVPN one, but it doesn't switch on for chatterino and I have to restart (may be an issue with my config or so), or I can just keep using chatterino on the non-vpn'd network

**Comment by pajlada** [comment]
This PR (#1476) should improve the reliability of the reconnect feature. Artifacts are available for testing for any VPN users: https://github.com/Chatterino/chatterino2/pull/1476/checks?check_run_id=371198630 -

**Comment by SLCH** [comment]
Cool
On arch
- On changing PIA servers: after successful reconnect takes 4 seconds for ch2 to reconnect. Old version stays disconnected.
- No openVPN here

On windows 10
- On changing PIA servers: instant reconnect. On both new and old.
- (not sure if it is related to ch2 or openvpn client) ch2 doesnt detect connection to vpn if is already connected. If reconnect while being connected to vpn seems to use it - can tell since it reconnects on disconnect or reconnect of vpn (reconnects using no vpn, doesnt wait for it to connect)

**Comment by Chronophylos** [comment]
Works great with NordVPN on Linux
