### ISSUE TITLE
Take logs in smaller channels from local storage

### ISSUE THREAD

**Issue by rxuz** [Chatterino/chatterino2#1191]
Grab logs for a user from local storage if none are available from the online option. Or add option to choose between both. 

Will make moderation easier in unlogged chats.

**Comment by Mm2PL** [comment]
Online logging we used (OverRustleLogs) shut down months ago. This feature could be quite easy to implement by partially reverting b4eb56f36211463edb441d1de9119dd5d6fde0a4. Searching local logs for specific keywords is way easier than an online service, which is way I would still like to have this functionality.

###### Sorry for necropost :)

**Comment by zneix** [comment]
As mentioned above, we were forced to drop support for `/logs` command since online logs are no longer available.
@mm2pl Your suggestion gives a valid point and we could try hacking around b4eb56f as you said, however I don't think it's worth doing so as `/logs` have been deprecated for over a year now and I think that sudden reincarnation of it would only confuse users (it may be just me who thinks like this though, comment below if you think like we could still work on something as suggested in the issue).
