### ISSUE TITLE
Bttv personal emotes

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#12]

**Comment by thegrowlx** [comment]
When will this be fixed/released?

**Comment by pajlada** [comment]
This issue is a pretty big undertaking, especially considering there's no public API support for this feature. Don't expect this to be implemented any time soon.

**Comment by Roger-Chavez** [comment]
> This issue is a pretty big undertaking, especially considering there's no public API support for this feature. Don't expect this to be implemented any time soon.

I requested for personal emotes to be added to the API and I was given the following reply: "They will never be part of the API because loading personal emotes via API does not scale. Other clients would need to reimplement our websocket handling:" https://github.com/night/betterttv/blob/master/src/socket 

[Link to github issue](client.jshttps://github.com/night/betterttv/issues/3853#issuecomment-627792090)

**Comment by Mm2PL** [comment]
https://github.com/night/betterttv/blob/master/src/socket-client.js
Your link is broken, here's a working one

**Comment by leon-richardt** [comment]
Implementation might make use of [QWebSockets](https://doc.qt.io/qt-5/qwebsocket.html).

**Comment by fourtf** [comment]
This issue is out of scope of the chatterino project.

**Comment by Mm2PL** [comment]
@fourtf another issue that would be best left open so there would be less dupes

**Comment by zneix** [comment]
And also pinned, since this is also something I personally get asked a lot by other Chatterino users.
