### ISSUE TITLE
Own messages not being shown in chat/not sending

### ISSUE THREAD

**Issue by zamusek** [Chatterino/chatterino2#1213]
**Describe the bug**
Messages not being shown in the chat when sent, not being sent at all, only happens in channels where the chat is fast

**To Reproduce**
1. Type a message in the chatbox
2. Press send
3. Message won't show up in the chat

**Expected behavior**
I expect the message to show in the chat

**Chatterino version**
2.1.0 (18.08.2019 9a7bb97-1)

**Comment by RAnders00** [comment]
This is a behaviour of Twitch that we have no influence on. Fast chats pause and resume to limit the number of messages, and this is done by twitch server-side. You have to send your message while the chat is "moving" for the message to be delivered.

I suspect you are surprised by this behaviour because this doesn't happen in web chat. Web chat simply lies to you and makes you think your message was sent even though it was dropped by the server. Chatterino connects to the chat service differently and shows you what messages are truly delivered to chat, and can therefore show you if your message was delivered or not, which web chat cannot/will not do.

**Comment by leon-richardt** [comment]
If you want to make sure your message got sent, you should check out #1181.

**Comment by fourtf** [comment]
Closing since this is unrelated to chatterino

**Comment by andria-dev** [comment]
Does Chatterino get any form of confirmation that your message was received by the server and not dropped? If so, I think it'd be possible to inform the user the message wasn't sent or try again until it's sent. If not, is Twitch just silently dropping the message?

**Comment by Felanbird** [comment]
> Does Chatterino get any form of confirmation that your message was received by the server and not dropped?

No

**Comment by Felanbird** [comment]
Also I'm locking this because this issue is from four years ago.

If you want to further discuss these facts please open a [new discussion](https://github.com/Chatterino/chatterino2/discussions/new/choose)
