### ISSUE TITLE
BTTV emotes not working in a specific channel

### ISSUE THREAD

**Issue by pajlada** [Chatterino/chatterino2#1275]
**Describe the bug**
BTTV channel emotes don't work in channel `tene__`

**To Reproduce**
Open up channel `tene__` and look at BTTV channel emotes

**Expected behavior**
A list of the BTTV channel emotes (you can see them on normal web chat)

**Chatterino version**
2.1.1

**Comment by Evanito** [comment]
Error is on BTTV's end. 
Compare:
 - [BTTV emote API response for `tene__`](https://api.betterttv.net/2/channels/tene__) (Zero emote response)
 - [Same request for a non-bugged channel `dogdog`](https://api.betterttv.net/2/channels/dogdog) (Expected response)

Possible cause is due to `tene__` only having .gif emotes? We can't say.
I would say this isn't our problem but it doesn't explain how webchat sees them fine.

**Comment by pajlada** [comment]
BTTV V3 API seems to work

[tene__](https://api.betterttv.net/3/cached/users/twitch/257151910)
[pajlada](https://api.betterttv.net/3/cached/users/twitch/11148817)
