### ISSUE TITLE
Having a problem staying connected to a chat

### ISSUE THREAD

**Issue by onobarcode** [Chatterino/chatterino2#1399]
**Describe the bug**
For the past two days I keep getting a disconnected/reconnected message on chatterino whenever I'm using my Twitch account, but seems to work fine when I switch to the anonymous account. I've changed password on my Twitch account, I've removed and readded my Twitch account to chatterino multiple times, and went to the connection settings on Twitch to disconnect the chatterino client but nothing has fixed the issue. 

It still seems to somewhat work, I can still type in chatterino and my messages go through to Twitch chat but not all of Twitch chat messages make it through to chatterino

**Screenshots**
Looks like this on an offline chat https://gyazo.com/36b3093e40087a2d4b5230e5537a4846
And like this on a live chat https://gyazo.com/6dc6688fa215e49c01888904c6eb4e6f
Chatterino and Twitch chat side by side https://gyazo.com/2d03a8ab9b77b66076016bab46f3fc5d
Gif of using chatterino and it goes through to Twitch https://gyazo.com/cfa00e7a3dc7d3d4f77a357938d0bb96

**Chatterino version**
Chatterino 2.1.5 (commit c6e1a1de2)

**Operating system**
Windows 10 Home

**Comment by Felanbird** [comment]
I can confirm this issue exists but I have no idea why.

~~I've replicated this issue on cbd93f9 and the issue only persists on that build with >34 channels.~~
~~I generated a portable instance of ce90253 and imported the exact same windowlayout.json file and was unable to replicate the disconnects.~~

![image](https://user-images.githubusercontent.com/41973452/67925428-b8247880-fb89-11e9-8850-e90cc6813f01.png)

As you can see from my messages in this image, while attempting to take this screenshot to prove my earlier point, I was able to generate the issue on ce90253 , but I have been unable to re-replicate it since.

I'm going to test ce90253 for a channel limit and see what happens, (I'm thinking the disconnect issue I previously replicated only happened because I opened both ce90253 & cbd93f9 at the same time)

**Comment by onobarcode** [comment]
So you're saying if I roll back to a previous release it may resolve this? I did used to have a lot more channels a few months ago without any issues. How do I download the specific ce90253 like you tried?

**Comment by Felanbird** [comment]
damn I edited my comment but you already posted @onobarcode , a better question I should've asked you originally is do you have >100 channels.

**Comment by onobarcode** [comment]
Omg I think you were already heading to the right direction with this. I was at 103, removed 3 channels and now it's working just fine. 100 seems to be the limit?

**Comment by Felanbird** [comment]
@onobarcode Yes, we originally we believed that 100 was the limit now, but there were a few people who had the issue with <100 , which is why I was doing "indepth" testing that I mentioned in my original comment.
but then it dawned on me that the >100 issue might be the issue you were having so I thought I'd ask that instead and now here we are 🙂

**Comment by Felanbird** [comment]
I have no idea why the limit is 100, it's an extremely new issue (the past few days) and as you saw in my original comment, not consistent with old versions of Chatterino.

and no problem 🙂
