### ISSUE TITLE
Tab completion can be canceled by unrelated keys.

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1404]
**Describe the bug**

Pressing certain keys cancels tab completion.

**To reproduce**

  1. Type an emote prefix, like `paja`
  1. Press tab once to complete to the first emote
  1. Press one of the keys from the list.
  1. Press tab again
  1. Notice that you cannot complete anymore.

List of ~~broken keys~~ keys that have this behaviour:
  * Caps lock
  * Num lock
  * Insert
  * Pause
  * Scroll lock
  * Print screen
  * F12
  * F11
  * F9
  * F8
  * F7
  * F6
  * F4
  * F3
  * F2
  * F1
  * Super (Windows key on Windows is untested)
  * Alt graph
  * Probably more.

**Chatterino version**

Chatterino 2.1.5 (commit a12bd3df1)

**Operating system**

Linux.

**Comment by alazymeme** [comment]
FeelsDankMan Slapp Mm2PL
I'll test this when I get back in an hour

**Comment by Mm2PL** [comment]
FeelsOkayMan

**Comment by alazymeme** [comment]
Found something interesting with this. Take for example nymn, since A is the first letter in the alphabet, it first tabs to `nymnA`. However `nymnA` also prefixes `nymnAww` - this leads me to believe that it's intentional behaviour as when I type `nymn`, hit tab (it tabs to `nymnA`), but if I hit caps lock (or equivalent) and hit tab again; it will complete to `nymnAww` - hence leading me to believe that it's entirely intentional

**Comment by Mm2PL** [comment]
It would make sense that `Escape` or `arrow keys` cancel it and that has to be intended but I'm not so sure about others.

**Comment by alazymeme** [comment]
@Mm2PL I think those are grouped as "modifier keys" - it might be a little difficult because you might have to individually exclude those keys or something
