### ISSUE TITLE
Build with system fmt

### ISSUE THREAD

**Issue by tim77** [Chatterino/chatterino2#1444]
Hello. Is it possible to build chatterino2 with system `fmt`, not bundled? This could help with pushing chatterino2 into official repos of some Linux distros since some of them have strict requirements as for bundled libs. Maybe also some other libs could be unbundled as well?

**Comment by pajlada** [comment]
We can definitely look into this. Please list the libraries that are most important for you to be system-bound other than fmt.

**Comment by tim77** [comment]
TBH most important is cryprographic libs and OpenSSL already unbundled, which is nice. But seems like you bundled not for no reason other libs since they are patched... Ok, would be nice if we unbundle this:

```
fmt
libcommuni
rapidjson
websocketpp
```

Note: i consulted with other maintainers and seems like this is not mandatory but recommended.

**Comment by pajlada** [comment]
@tim77 Please see my approach #1447 - I've currently only added support to compile with system version of fmt.
In short, you can pass two extra flags for fmt right now:
`FMT_PREFIX=/path/to/fmt` to compile Chatterino with your own source and header folder
`FMT_SYSTEM=1` to link Chatterino with system fmt
Do note that fmt needs to be version 4 for it to work with Chatterino (which is why it's a submodule/included in the project in the first place)

**Comment by pajlada** [comment]
I've merged #1447 into master now, so I'll close this and make a new issue for updating the fmt lib version
