### ISSUE TITLE
Messages caught by AutoMod don't show which word was profane

### ISSUE THREAD

**Issue by 5E7EN** [Chatterino/chatterino2#1504]
**Describe the bug**
When AutoMod catches a message in a channel when using WebChat, the message is shown for approval and the questionable phrase is highlighted. This is not the case in Chatterino though. Instead, it just shows the entire message without any phrase highlighting.

**To reproduce**
Enable AutoMod in your channel, open chat windows in both Chatterino and WebChat and on another account, type a phrase (along with other text for better clarity) that would typically get caught based on your AutoMod rulesets and compare the results.

**Screenshots**
Chatterino: https://i.imgur.com/TBqNNqV.png
WebChat: https://i.imgur.com/P2H7HGZ.png

**Chatterino version**
Chatterino 2.1.7 (commit 845c8fa63)

**Operating system**
Windows 10

**Additional information**
This would be especially useful when moderating channels with foreign languages when AutoMod still catches messages.

**Comment by 5E7EN** [comment]
Accidentally added the wrong labels to this issue. This is a bug report.

**Comment by apa420** [comment]
The automod endpoint currently only returns the message in question, it's id and what type triggered the bot. We can't know what caused it.

**Comment by Mm2PL** [comment]
Could this be revisted after discovering `@flags`? ![if you see this i von](https://cdn.betterttv.net/emote/5e879f2cacae25096140c8a9/1x)

**Comment by pajlada** [comment]
> Could this be revisted after discovering `@flags`? ![if you see this i von](https://cdn.betterttv.net/emote/5e879f2cacae25096140c8a9/1x)

Could you elaborate?

**Comment by Mm2PL** [comment]
> > Could this be revisted after discovering `@flags`? ![if you see this i von](https://camo.githubusercontent.com/7a322706dc77da7d089bbdc56d7e4b0231caaa1f286b4447ca33f4a4b28e239b/68747470733a2f2f63646e2e6265747465727474762e6e65742f656d6f74652f3565383739663263616361653235303936313430633861392f3178)
> 
> Could you elaborate?

The undocumented\* `flags` IRC tag includes automod flags/detections in a message.
\* I described flags in  chatterino/chatterino2#1772 in more detail.

**Comment by iProdigy** [comment]
> > > Could this be revisted after discovering `@flags`? ![if you see this i von](https://camo.githubusercontent.com/7a322706dc77da7d089bbdc56d7e4b0231caaa1f286b4447ca33f4a4b28e239b/68747470733a2f2f63646e2e6265747465727474762e6e65742f656d6f74652f3565383739663263616361653235303936313430633861392f3178)
> > 
> > 
> > Could you elaborate?
> 
> The undocumented* `flags` IRC tag includes automod flags/detections in a message.
> * I described flags in #1772 in more detail.

since the message was caught by automod, it hasn't been sent over irc yet so there is no `flags` tag to inspect


> The automod endpoint currently only returns the message in question, it's id and what type triggered the bot. We can't know what caused it.

now, on `automod_rejected` under `chat_moderator_actions`, one can inspect `args` to get the problematic phrase & reason

example (phrase is `shit`, reason is `profanity`): `{"type":"MESSAGE","data":{"topic":"chat_moderator_actions.493418343.53482260","message":"{\"type\":\"moderation_action\",\"data\":{\"type\":\"chat_login_moderation\",\"moderation_action\":\"automod_rejected\",\"args\":[\"ogprodigy\",\"shit\",\"profanity\"],\"created_by\":\"\",\"created_by_user_id\":\"\",\"created_at\":\"\",\"msg_id\":\"44ede2ad-c88e-4038-baee-1ae049437fff\",\"target_user_id\":\"53888434\",\"target_user_login\":\"ogprodigy\",\"from_automod\":false}}"}}`

(note: this is only present for moderators & not even the user who sent the offending message)
