### ISSUE TITLE
Emojis only work with the EmojiOne 2 emoji set

### ISSUE THREAD

**Issue by Karabast** [Chatterino/chatterino2#1531]
**Describe the bug**
Emojis are only visible when the EmojiOne 2 emoji set is selected

**To reproduce**
Select any other emoji set than EmojiOne 2 and type an emoji

**Screenshots**
https://i.imgur.com/xBNvqJb.png
https://i.imgur.com/2EPSjz0.png
https://i.imgur.com/UTOSc0R.png
https://i.imgur.com/L4sk3sW.png
https://i.imgur.com/ClfGfCI.png
https://i.imgur.com/3XTbhLy.png
https://i.imgur.com/bfjGuNM.png

**Chatterino version**
Chatterino Nightly 2.1.7 (commit b8953157c, )

**Operating system**
Windows 10 Pro Version 1803

**Additional information**
Tried clearing Chatterino cache, didn't help.

**Comment by leon-richardt** [comment]
They work for me (b8953157c, Windows 10 Pro 1903).

![emojis_working](https://user-images.githubusercontent.com/35232120/73691056-e0b09700-46d1-11ea-8d30-0b54c1800a6b.png)

**Comment by Karabast** [comment]
Do you have any idea what might be causing this?

**Comment by leon-richardt** [comment]
Actually, I can reproduce on Arch and b895315.

> Do you have any idea what might be causing this?

Looking at the code, it looks like this might be a provider issue: All emoji sets are provided by the pajbot website but EmojiOne 2 is served by a different provider:

https://github.com/Chatterino/chatterino2/blob/master/src/providers/emoji/Emojis.cpp#L248-L263

I might not have noticed this on Windows because of caching, I suppose.

**Comment by pajlada** [comment]
For reference, this was caused by downtime of the server
