### ISSUE TITLE
More documentation required?

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#1541]
As someone in the discord recently said that the documentation was not sufficient i want to ask the question he and start a discussion.

Is more documentation required for Chatterino? If so, what types of documentation?

**Comment by Mm2PL** [comment]
Docs are good,
the first idea that came to my mind is an index of where functionality is located

**Comment by TranRed** [comment]
I think if someone from discord wants to add documentantion, they just should create a PR. 🙂

**Comment by leon-richardt** [comment]
> I think if someone from discord wants to add documentantion, they just should create a PR. 🙂

I think the problem is that people want to contribute but have a hard time getting started with the code base.

As mentioned by @Mm2PL, I also had a hard time navigating the code structure in the beginning. (And as a matter of fact, I still have problems locating some functionality today.)
Part of it is natural, I think, but part of it could be helped by having more comprehensive (and "coherent") documentation.

IMHO, if we could all agree on a common approach to documentation, it would be very beneficial for the project.
