### ISSUE TITLE
Option to merge the Channel BTTV and FFZ emotes lists in a single one

### ISSUE THREAD

**Issue by bennyhillthebest** [Chatterino/chatterino2#1548]
**Is your feature request related to a problem? Please describe.**
Since BetterTTV upped the number of available slots per channel i feel that BTTV and FFZ separated lists are a "waste of screen real estate", so i think a single list would be cleaner. Also this "feature" could be applied to all the other emotes window tabs.

**Describe the solution you'd like**
I would say that two lists have their use cases so i think the better solution would be a switch in the program preferences 

**Describe alternatives you've considered**
I think it's kind of a binary situation

**Comment by fourtf** [comment]
Having the categories is important to let people know where emotes come from. Some people may not even know that BetterTTV or FrankerFaceZ exists. It also allows users to quickly find the emotes they want if they know from which host they are. Furthermore I don't see the argument of "screen space wasted" if the titles are only 5% of the entire space (since there are so many bttv emotes).

Adding a setting for this is not an option, as there is presumably close to no users that would use it, meaning that more users would be confused by the setting.
