### ISSUE TITLE
Notification about messages going missing

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1600]
**Is your feature request related to a problem? Please describe.**

The problem is that there is no feedback that a message that the user sent has gone missing. Currently if the user is "globally banned" their messages just don't show up.

**Describe the solution you'd like**

I would like for Chatterino to show a message, if something doesn't go through. The message could be something like: **Your message didn't go through, it could have been filtered out by a spam filter or you might be currently globally banned or rate limited**.

**Describe alternatives you've considered**

Not doing it, periodically dismissing bugs like #1599.

**Additional context**

See #1599

**Comment by apa420** [comment]
Things that might cause the message not going through:
 - Bad internet that might drop incoming messages even though yours got sent
 - Big chats getting spammed twitch will filter out some messages because there are simply too many
 - You've been gotten ratelimited in chat because you're typing not only in chatterino but somewhere else too
 - What happens when you can't even type in the chat, i. e. there is slowmode, r9k, you might be banned, it might be in submode etc.

I think there are too many potential problems leading to the issue of the message not being sent. I don't think there should be a message for that. Also there are not that many people who write the issue you're describing.

**Comment by pajlada** [comment]
With chat send through Helix, most of these things will have been fixed. The user will at least get some sort of feedback that they're message hasn't gone through.

There might be a few scenarios where we still don't know if the message came through or not, but I don't think it's reasonable to do the type of mesage/state handling required for that functionality.

In my opinion, we can close this when the default Chat Send Protocol is set to Helix instead of IRC.

**Comment by pajlada** [comment]
For reference, we have reverted back to IRC as the default chat send protocol due to some functionality being lost.

**Comment by pajlada** [comment]
I don't think there's a reasonable way to achieve this without platform support. Switching chat send protocol to Helix will fix a lot of these, but it has some downsides. I think our best bet is to try to improve Helix chat send support & report bugs as we see them, and eventually swap over to that.
Closing this as fixed as there's nothing intended to be done specifically about this in Chatterino.
