### ISSUE TITLE
Use of qDebug() spams the system log / journal

### ISSUE THREAD

**Issue by coledot** [Chatterino/chatterino2#1601]
**Describe the bug**
When Chatterino logs debug messages, it does so using qDebug(). On my system (Arch Linux, though I assume this applies to any distro using systemd) this puts the debug messages into the system journal. After a while these messages get to be horribly spammy and waste space in the system logs. This sort of debug logging ought to be placed in a separate debug log file, stored at the user level, ideally with an option to turn off debug output entirely.

**To reproduce**
1. Fire up Chatterino.
2. Run in a shell: `sudo journalctl -b | grep chatterino`

**Chatterino version**
Chatterino 2.1.7 (commit 5ad427bd6)

**Operating system**
Arch Linux

**Comment by leon-richardt** [comment]
Additonally, I feel like many debug messages are artifacts of feature development and serve no real purpose at the current point in time.
It might make sense to purge those stray messages in a PR.

**Comment by Mm2PL** [comment]
This might be caused by output of Chatterino being treated as output of another process, your file manager, session process, or what ever you used to start Chatterino. 
Best mitigation I can think of (if that hypothesis is true) is that you should start Chatterino in a virtual terminal or using a shell script that redirects `stdout` and `stderr` to a file like `/dev/null`. So something like this should do.
```
#!/bin/bash
/path/to/bin/chatterino 2>/dev/null 1> /dev/null
```

**Comment by pajlada** [comment]
I agree with @leon-richardt - there's definitely a lot of debug output we could get rid of.

After testing this on my system I don't get any output in systemd (Arch Linux as well btw). tested running chatterino from dmenu

Will leave the issue up as a "clean up debug output" reminder

**Comment by thekalio** [comment]
I have seen this behavior on Arch Linux as well. The reason is that [qt5-base](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/qt5-base) is built with `./configure -journald`, which causes Qt 5.6+ to log to journald/syslog if not attached to a terminal ([more information here](https://www.ics.com/blog/whats-new-qt-560-logging-syslog-and-journald)).

The solution: export the environment variable `QT_LOGGING_TO_CONSOLE=1` to direct Qt logs to stderr in all cases instead of journald/syslog.

**Comment by zneix** [comment]
Is this still an issue? Doesn't happen on my Debian using 2.2.2 Stable.

**Comment by zneix** [comment]
@coledot we've recently had a rework regarding logging (see #2206) and moved away from plain `qDebug()`'s. Does that resolve the issue?

**Comment by coledot** [comment]
:+1: 
Works for me!
