### ISSUE TITLE
Chat freezing when going too fast.

### ISSUE THREAD

**Issue by tsukijin** [Chatterino/chatterino2#1657]
**Describe the bug**
Chat freezes every few seconds when chat is going too fast. I'm not sure if it's because of the amount of messages, or other reasons. My guess is that this is a limitation of the API, but I have no clue.

**To reproduce**
Just open a chat that has a lot of messages sent constantly (xQcOW, for example), and you'll see it. Well, maybe I guess. 

**Screenshots**
Example of the freezing: https://gfycat.com/livelynimblecanadagoose

**Chatterino version**
Chatterino 2.1.7 (commit 845c8fa63)

**Operating system**
Windows 10

**Comment by Mm2PL** [comment]
To my knowledge this is not a Chatterino issue.
What I see in the video you have provided is the chat *buffering*, almost like an online video would.

**Comment by tsukijin** [comment]
> 
> 
> To my knowledge this is not a Chatterino issue.
> What I see in the video you have provided is the chat _buffering_, almost like an online video would.

Thinking about it more, I feel like it's something on my end, but I have no idea what it could be. Settings don't seem to change anything. I couldn't find any other issues for this problem either which also makes me believe it's only me as well. 
I've just noticed that my chat messages aren't sent when it's frozen/buffering like this.

**Comment by Mm2PL** [comment]
does this happen on other clients, like web chat and Chatty for example?

**Comment by tsukijin** [comment]
In normal twitch chat it happens as well but it's not as bad. Chatty is about the exact same as twitch chat.

**Comment by 5E7EN** [comment]
This is intentional behavior and has nothing to do with Chatterino. Any IRC client connected to Twitch will have this "buffering" when a chat is going quickly.

Not exactly sure why it was implemented (maybe to help moderators moderate in a fast-moving chat?), but to prove it isn't Chatterino, notice how mods and VIPs seem to "bypass" this pausing period (in this case, Fossabot) and messages they send are actually seen.
Additionally, the average user that sends a message during this time period will have it dropped and not displayed to other chat members (unless, of course, the conditions mentioned above are met).

**Comment by tsukijin** [comment]
I see, I didn't even notice the bot bypassing it. I also asked my friends and they said that it's the same for them. Well, I guess that's that.
