### ISSUE TITLE
Show FFZ specialty chat badges

### ISSUE THREAD

**Issue by robmonte** [Chatterino/chatterino2#1658]
Users are capable of donating to FFZ to receive an "FFZ Donator" chat badge next to their username. Considering that Chatterino is a consumer of FFZ and BTTV, (and maybe FFZ:AP, but that one is questionable), it is right to respect these features to showcase those who have supported either of those addons. If there is currently no way to receive that information, communication should be extended to request support for this.

**Comment by cinemassacres** [comment]
https://github.com/Chatterino/chatterino2/pull/1662

**Comment by gempir** [comment]
@SirStendec is this something we should implement in your opinion. This would also heavily hit the FFZ API since every users has to be checked atleast once for a badge.

Or do you solve this another way that I'm not thinking about right now?

**Comment by SirStendec** [comment]
We have a single access point that returns information on all FFZ badges and all users that should have such a badge. Currently only v1 of our API is accessible, and it uses usernames to identify users. The official client uses this endpoint, and will do so until v2 is available.

https://api.frankerfacez.com/v1/badges

API v2, when it's ready, will reference users by Twitch ID rather than username. I also plan to only return records for active users who have used Twitch within the past week or two when this goes live, to prune out some of the old records. We're really getting a lot of users with the badge...

**Comment by apa420** [comment]
This point has been in debate a couple times before whether or not chatterino should include 3rd party donator badges such as the bttv pro or ffz supporter one.

**Comment by Mm2PL** [comment]
The badges could probably be turned off like other ones, it would not hurt to add this. In my opinion we should honor FFZ's and BTTV's donators since we are using their services.

**Comment by alazymeme** [comment]
This one still needing triage? 🤔

**Comment by SirStendec** [comment]
Just wanted to comment here that I ended up adding an extra endpoint to APIv1 for FrankerFaceZ that returns badge assignments by Twitch ID rather than username. That can be found at https://api.frankerfacez.com/v1/badges/ids and should be preferred until FFZ's API v2 is ready.

The official client is using the new endpoint as of today. (I was refactoring how badges for supporters were stored in memory and decided I may as well take a little time to just get better data.)

**Comment by pajlada** [comment]
Solved in #2101 

For BetterTTV badges, please open a new issue (if there isn't one already)
