### ISSUE TITLE
Option to disable username color ajustments

### ISSUE THREAD

**Issue by KoenEU** [Chatterino/chatterino2#1681]
**Is your feature request related to a problem? Please describe.**
Chatterino automatically applies a color ajustment to usernames to ensure they remain readable. I would like the ability to turn this off.

**Describe the solution you'd like**
A checkbox in the settings to enable/disable the color ajustments.
Or if possible a more advanced setting similar to what FFZ does.
![firefox_Ubv12PFly6](https://user-images.githubusercontent.com/65124926/81504062-9ac62900-92e7-11ea-92c0-e41824cb6fe1.png)

**Comment by fourtf** [comment]
I have concerns since this makes some usernames unreadable and I believe that it doesn't add usefulness. Many settings, such as this, combined may increase the complexity of the settings ui (which hurts every user) but doesn't provide important benefits.

Why do you want this setting? Do you use this setting in FFZ and what benefits does it provide?

**Comment by KoenEU** [comment]
I'd want this setting so that my chat is more representative of what other users are seeing.
I do use it in ffz, and its very rare I see a username I struggle to read. I think the color ajustment is especially agressive towards purples and blues. 
Its of course nothing important, but I'd use it if the option was there.

**Comment by fourtf** [comment]
Just as a side note, the blue colors are the darkest so they need to be corrected the most

**Comment by fourtf** [comment]
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
