### ISSUE TITLE
Better emote window

### ISSUE THREAD

**Issue by 0xRainy** [Chatterino/chatterino2#1723]
**What should be added?**
When clicking on an emote in the emote window it should not remove focus from the chat text entry box so that you can click an emote and immediately hit enter to send it to the channel.

Secondly, clicking on an emote in the emote window should enter the emote text in the currently active channel, even when switching to a different chat tab.

**Why should it be added?**
Clicking an emote, then having to click onto the chat to hit enter to send it is silly and annoying.

Having to open a separate emotes window for each chat just to click an emote, click the chat box to send it, then close the emote window is also silly and annoying. Especially when watching multiple streams.

**Comment by fourtf** [comment]
This will be unexpected since another window will take the focus after you select an emote. I suggest using the `:` menu for this instead.

**Comment by Y0dax** [comment]
I agree with @0xRainy on this topic, I often want to add emotes quickly into the current channel. This is not easy to do with complex emotes or ones that have difficult to remember prefixes.

In the emote pickers current state, I understand not wanting to change the focus, Perhaps we should entertain the idea of making the emote picker a non-persistent popup much like twitches implantation rather than a standalone window. Along these lines, can be confusing as a separate window because it only enters emotes into the channel it was opened from. In the spirit of chatterino, using the current emote picker concurrently across several channels simultaneously is very difficult.

I'm curious what the benefit is from having it as a standalone window?

**Comment by CaptainFlint** [comment]
I also think that focus should automatically return to the chat field after clicking an emote. It is very rare that a user needs to have persistent focus in the emote window. And if the focus is indeed needed, clicking an emote is not a way to do it. You'll need to click the titlebar, or the empty space around the emotes, etc.

Also it could be implemented optionally, with a checkbox in settings, so that people could decide for themselves if they want the focus to autoswitch or not.
