### ISSUE TITLE
Emote Menu emote selection isn't working as intended?

### ISSUE THREAD

**Issue by trybefore** [Chatterino/chatterino2#1769]
**Describe the bug**
clicking emote in the emote menu wont necessarily put it where you want it to go

**To reproduce**
have 2 different splits in one tab and click the emote, it wont go to the bottom one

**Screenshots**
[https://i.imgur.com/HkFnAmN.gifv](url)

**Chatterino version**
Chatterino Nightly 2.1.7 (commit 8e202c375, )

**Operating system**
Windows 10

**Comment by trybefore** [comment]
it puts emote in the split u opened the emote menu in

**Comment by zneix** [comment]
You've opened the emote picker in upper split, thus emotes are going into the input box of the split for which emote picker was opened, not the focued one.
I think we can change emote picker's behavior, so emote will be going to focused split, instead of the one that you opened, but keep in mind that might result in picking invalid bttv/ffz emotes.
