### ISSUE TITLE
Remember Popped-up Chat Size

### ISSUE THREAD

**Issue by doximanman** [Chatterino/chatterino2#1788]
**What should be added?**
Add a feature that would save the size of a popped up chat. 
**Why should it be added?**
Right now whenever I popup a chat, its size is always the same, and it's very small so I have to resize it every time. Would be nice if there was a feature that would either keep the size I set it to last time or maybe a setting that would let me set a specific size (for eg. X by Y pixels).

**Comment by skullsir** [comment]
That's a cool idea, I assume you want the setting to be like `Chat Popup Window Size: ` then you select height and width?

**Comment by doximanman** [comment]
> That's a cool idea, I assume you want the setting to be like `Chat Popup Window Size: ` then you select height and width?
Yeah, that would be great.

**Comment by pajlada** [comment]
When a popup is resized, Window Manager should save a setting with the last size a popup window was resized to. This could be a ChatterinoSetting stored in `Settings.hpp`, or it could be stored in `window-layout.json`.
This setting will be hidden, and cannot be configured through the settings dialog.

**Comment by maliByatzes** [comment]
@pajlada I would like to take this issue.

**Comment by pajlada** [comment]
@maliByatzes Awesome! Let me know if you need any help

**Comment by maliByatzes** [comment]
@pajlada I've looked at some possible solution for this issue, and I have some questions.
When the Main window is closed `WindowManager::save()` is called and its saves all the windows currently open and their properties to `window-layout.json`. I looked into calling the `WindowManager::save()` also when the Popup window is closed but this will override the `window-layout.json` which I think is fine as long as the Main window is still open, but the `WindowManager::save()` is invoked again on some sort of timer so that will override any Popup window settings that may be set earlier. Any ideas on how to manage this situation.

Which also brings a new problem, is the `window-layout.json` settings re-read when a new Window is made because for the height and width for a new Popup window seems somewhat hardcoded:
```
this->resize(int(300 * this->scale()), int(500 * this->scale()));
```

**Comment by pajlada** [comment]
@maliByatzes I think since what we're trying to achieve is not saving the size or position of popup windows (this is already handled in the window layout), but rather the size of the next popup window you create, so it's the same as your most recently resized popup window.
For this reason, I think you should use a ChatterinoSetting instead

You'd want to add the setting into the `Settings.hpp` file, it could be 2 values (width & height) stored under the paths `/appearance/popup/lastWidth` and `/appearance/popup/lastHeight`, and set them on resize events.

Then you'd read those two values whenever a new popup is created

Let me know if that doesn't make sense and I can rethink it a bit
