### ISSUE TITLE
Decide whether or not certain highlights are included in the mentions tab

### ISSUE THREAD

**Issue by kehlery** [Chatterino/chatterino2#1793]
**What should be added?**
There should be an option added in the 'highlights settings' where you can decide whether certain terms or people are included in your mentions tab 
![ex](https://user-images.githubusercontent.com/40723238/86723256-9616ac00-bfdc-11ea-9b5c-c9f562bbede9.png)

**Why should it be added?**
having certain people highlighted is convenient but they often fill up your mentions tab with messages completely unrelated to you.
![ex](https://user-images.githubusercontent.com/40723238/86723509-d2e2a300-bfdc-11ea-9f69-1e37b10a96fb.png)

**Comment by leon-richardt** [comment]
From my understanding, this functionality would be included in https://github.com/Chatterino/chatterino2/pull/1748.

**Comment by Mr-Rixa** [comment]
This would be a great and very welcome addition. 👍 My mentions tab is currently completely useless 😅
No offense, I'm not a big fan of the filter coding approach richardt has created, since I can just use regex non capturing to achieve kinda similar results for what I'd do anyway, but a ☑️ for "ignore from mentions" would be the best. Clean and simple to use
