### ISSUE TITLE
Chrome extension moderator mode

### ISSUE THREAD

**Issue by Dinoslav** [Chatterino/chatterino2#1819]
In chrome extension everytime I change tabs, moderator mode gets disabled.

No idea if it's something on my end or a bug.

**Comment by Mm2PL** [comment]
What version are you running, 2.1.7 or nightly or even something older?

Mod-mode is stored per-split, not per-channel (checkable by creating a new split, setting mod-mode and changing channels).
**I have no way to confirm or deny this**, but it looks like this bug could be caused by re-creation of the split or even the entire window when switching tabs.

**Comment by Dinoslav** [comment]
Using Chatterino 2.1.7 (commit 845c8fa63). In the program itself it works great, only the extension has the problem.

P.S. sorry for the template, first time using GitHub

**Comment by Mm2PL** [comment]
You are using the 2.1.7 stable release (from December 2019), could you try updating to the [latest nightly](https://github.com/Chatterino/chatterino2/releases/tag/github-actions-nightly) to see if this still happens? 🙂

**Comment by Dinoslav** [comment]
Tried the nightly version, still same problem. Made a [gif](https://gyazo.com/b92fbd3d94d060d0b1719067649ee7dc) that shows what is happening, if it helps.

**Comment by Mm2PL** [comment]
I inspected the Chatterino source code and the browser extension, the Window and Split seem to be deleted every time you switch tabs or otherwise make Chatterino detach. This doesn't seem like an issue that can be solved easily 🙁

**Comment by Dinoslav** [comment]
Thats unfortunate :/

**Comment by srnyx** [comment]
Feel like this can be easily solved.
Just add an option to have moderator enabled by default.
