### ISSUE TITLE
Notifications don't work

### ISSUE THREAD

**Issue by Kazekai** [Chatterino/chatterino2#1826]
Enabling desktop notifications in the settings menu doesn't give me any notifications, tested with both sending messages into my own twitch chat through browser, and asking someone else to do it.

**To reproduce**
As described, it just doesn't work. I have no idea what I'm doing wrong or if it's just broken for me.

![image](https://user-images.githubusercontent.com/9657399/88490851-6704b200-cf6c-11ea-925e-08d348b90683.png)

**Chatterino version**
Chatterino 2.1.7 (commit 845c8fa63)

**Operating system**
Windows 10 64bit

**Additional information**
Having desktop notifications was basically the only reason I wanted a desktop chat client because my stream is so small that the chat is empty most of the time. Instead of having to babysit the chat, I would've liked to just go about my business and worry about it when I was certain someone was actually in there.

**Comment by leon-richardt** [comment]
These are notifications for when a channel goes live; not when someone sends a message in chat.
If you want notifications on new messages, there is another thing you can do. (Note that this is more of a "hack" rather than an intended feature though.)

1. Navigate to your "Highlights" tab and add a new highlight.
2. For "Pattern", enter `.`.
3. Tick the box in the "Enable regex" column.

It should look somewhat similar to this:
![highlights_tab](https://user-images.githubusercontent.com/35232120/88532374-c7dfc900-d004-11ea-873e-277a27a2affe.png)
(You can ignore additional columns; these are from the latest nightly build.)

This setup will not generate a toast notification but it will flash your taskbar and play a highlight sounds. Note additionally that this highlight will trigger in **all** splits you are in so you should probably only have your own channel open in Chatterino while this highlight is enabled.
