### ISSUE TITLE
A confirmation for potentially unwated usercard actions

### ISSUE THREAD

**Issue by Leeqo** [Chatterino/chatterino2#1886]
**What should be added?**
A confirmation box when following/unfollowing someone.

**Why should it be added?**
not to follow or unfollow people by accident

**Comment by Mm2PL** [comment]
rip follows from chatterino. https://discuss.dev.twitch.tv/t/deprecation-of-create-and-delete-follows-api-endpoints/32351/10 ![FeelsWeirdMan](https://cdn.frankerfacez.com/emote/131597/1)

**Comment by zneix** [comment]
Due to twitch soon removing API for (un)following other users this is now irrelevant. Im the discussion mm2pl linked, it was said that Helix endpoints will stop functioning on 27th July. I'll keep the issue open until then in case anything changes (for better, hopefully ![zneixCope](https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_841e0ef3878b49cd9eaff86c65cb87a3/default/dark/1.0)).

**Comment by zneix** [comment]
As requested in #3023, there's also a possible usecase for adding confirmation for blocks, so I'm going to change the title of the issue.
