### ISSUE TITLE
Can't change colors for whispers anymore

### ISSUE THREAD

**Issue by VulpesHD** [Chatterino/chatterino2#1922]
I was able to change the highlight color of my whispers in the past, but in the newest updates it seems to be missing.

**Comment by leon-richardt** [comment]
This was brought up in https://github.com/Chatterino/chatterino2/issues/1893#issuecomment-678678718. I Twitch chat, @fourtf mentioned he found a bug with the feature , although he didn't recall what exactly was wrong.

The feature could easily be re-enabled since the code is still there but I'm not sure if @fourtf is comfortable with that.
