### ISSUE TITLE
chatterino not launching

### ISSUE THREAD

**Issue by Gamesjed** [Chatterino/chatterino2#1957]
**Describe the bug**
Chatterino not launching

**To reproduce**
just launching the app makes it crash

**Chatterino version**
Latest

**Operating system**
windows 10

**Comment by fourtf** [comment]
Hey, since there isn't much information I can only suggest a couple things:

- Make sure you have the Visual C++ Redistributable installed (available in the installer) **AND** have restarted your computer after.
- Try running Chatterino in Administrator mode once. I am not quite sure why but this has worked for me.
- If nothing else works you can try resetting your settings using the "fresh install" option in the installer
![image](https://user-images.githubusercontent.com/6320036/93000337-01728200-f528-11ea-9668-3c1dd44a8f7b.png)


I'll close the issue to keep things clean.
