### ISSUE TITLE
Regarding colorizing gray names

### ISSUE THREAD

**Issue by L7mon** [Chatterino/chatterino2#2096]
**What should be added?**

The option "Colorize users without color set (gray names)" should be off by default instead of on.
**Why should it be added?**

I think most people would rather the color be accurate and it shows if an account is new.

**Comment by apa420** [comment]
People who are new to twitch get very confused with the grey usernames that are in chatterino. Making the default to be colorized makes more sense since you get less question from the newer people who start out with chatterino. For people who already use chatterino they know there is probably a setting to enable that.
