### ISSUE TITLE
highlights for mentions dont work on new realease 

### ISSUE THREAD

**Issue by 69bob420** [Chatterino/chatterino2#2105]
**Describe the bug**
highlights dont show up for mentions

**To reproduce**
update to new install

**Screenshots**

**Chatterino version**
Chatterino 2.2.3-beta (commit 3c6e6446c)

**Operating system**
windows 10

**Additional information**

**Comment by leon-richardt** [comment]
Fixed by #2090 once it's merged.

**Comment by alazymeme** [comment]
Hello 69bob420

Filling out the fields of the issue template greatly assists developers in reproducing and solving the issue. Please would you kindly follow the template as indicated in the issue template. As @leon-richardt also mentioned, this issue is a duplicate. Please would you kindly use the search function in the issues section in order to locate a related issue before creating a new one.

I appreciate your assistance.

Kind Regards
ALazyMeme

**Comment by 69bob420** [comment]
i did guess my search had to specific keywords
sorry
