### ISSUE TITLE
Font selection should work as an input box, not a suggestion box

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#2114]
**What should be added?**
The ability to type your font and add it from a list. If you type slow, then it will select a different font for every letter. It should work as an input box, not a suggestion box:

![lol](https://i.alazymeme.com/BlueFixedImage.gif)

**Why should it be added?**
The current implementation seems old and outdated

**Comment by fourtf** [comment]
I don't think that this is worth changing. IMO it requires too much effort to recreate the Dialog and get all the functionality including preview, selecting all fonts properly and testing.

**Comment by alazymeme** [comment]
> I don't think that this is worth changing. IMO it requires too much effort to recreate the Dialog and get all the functionality including preview, selecting all fonts properly and testing.

Can you suggest anything else? Currently I find it a bit of a pain to change my font.

**Comment by fourtf** [comment]
Here is my suggestion:
1. Accept that it is a subpar experience for yourself. Even if you are used to a certain way that ui works take a moment to analyse the way another system does it. It may be a refreshing experience to realize that there are multiple ways to achieve a goal in ui design! In this case it works similar to a couple of elements in the windows operating system. The windows file explorer for example uses the same system to select items quickly. As such users of the system will already be used to the way a certain dialog operates.
2. Only change your font so often. Stick to a font that you enjoy using for a longer time. I now realize the level of zen I get  by sticking to the same font without feeling the need to change it. However, if you still feel a strong compulsion to change your font often enough to trigger a negative experience in the dialog experience my advice would be, as mentioned in 1., to try and accept that this is a minor part of the Chatterino experience we are trying to create. The important part is to allow the user to select a font in case he has trouble reading the default one. This should be done without hassle in a familiar environment that the user is already accustomed to. In our case, since qt is such a popular framework, the user may have even used the same dialog in another application! Most other font dialog also look and behave similar.
3. Selecting a font is only done in a single place - to select the chat font. This also means that if work put in is proportional to the  time a user uses the program this would mean that there shouldn't be a lot of development time spent on this dialog. It already achieves its goal quite well! It shows all the available fonts on the system and let's the use select one of them. This is the exact functionality wanted from this component! The important feature therefore is already provided by the framework with a level of quality that we can rely on. With the amount of development time proportional to user time spent using the feature we can't possibly justify doing our own implementation of this dialog.we can simply not reasonably allocate enough resources to fix this issue. The time would be better spent in other places. Quite upsettingly this issue does not seem to have any concept of what important for the users of this program is. It seems to be a minor annoyance posted to an issue without further thought.
4. Realistically, what does it take to fix this? It requires a full reimplementation of the font dialog. We can of course not base it off of qts own version because of licensing issues. Adding an external dependency is not worth it compared to the payoff in any capacity. It is simply out of scope to "fix" this. It isn't even broken.
