### ISSUE TITLE
Posting too many characters in IRC makes you disconnect

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#2122]
**Describe the bug**
Posting too many IRC characters will disconnect you from the IRC server

**To reproduce**
1. Connect to an IRC server
2. Post a lot of characters

**Screenshots**
![image](https://user-images.githubusercontent.com/12804673/97102249-abc8f200-16ef-11eb-9a13-6a6c6c150291.png)

**Chatterino version**
Chatterino Nightly 2.2.3-beta (commit ec9486948, 24.10.2020)

**Operating system**
Windows 10

**Additional information**
Also disconnects for @Felanbird

![image](https://user-images.githubusercontent.com/12804673/97102384-b46df800-16f0-11eb-9012-9cfa76a92643.png)

**Comment by pajlada** [comment]
does it reconnect @alazymeme ?

**Comment by alazymeme** [comment]
Yes

**Comment by pajlada** [comment]
Not a bug the, the disconnect happens on the IRC servers side throwing you out because you broke some rule.

These rules might be different from IRC server to IRC server - for Twitch we have pretty deep support so it's easy for us to implement certain limits for when you send messages, but different IRC servers will have different limits and reasons for throwing you out.

If anything, there may be some "reason for kick" message we're able to pick up, but that doesn't fit into the bug category.

**Comment by alazymeme** [comment]
@TETYYS Is there a character limit on your server?

**Comment by TETYYS** [comment]
Probably, yes
