### ISSUE TITLE
Settings option to disable the update arrow

### ISSUE THREAD

**Issue by bennyhillthebest** [Chatterino/chatterino2#2163]
**What should be added?**
An option to disable the update arrow from appearing when the application is launched.

**Why should it be added?**
Chatterino on my system is built and updated seldomly by looking at new features in the commit log (Debian i686), so firstly i don't think i can simply download and install the new update, secondly it's a bit of nag having the arrow appearing everytime the application is launched. Of course it's a very minor request, so do as you like.

**Comment by pajlada** [comment]
I am working on a PR to "normalize" the update skipping behaviour.

On Windows, you skip any sort of update checks if you have downloaded a Nightly version. I will make this apply to macOS and Linux too. To apply this behaviour, you can add the `nightly` mode to your modes file (the modes file is read from the same folder as the chatterino2 binary is located)

See #2164

**Comment by bennyhillthebest** [comment]
Tried setting `bool isNightly{true};` in Modes.hpp or commenting the 19 to 26 lines of Modes.cpp except for `this->isNightly = true;`, but QtCreator laments that it doesn't recognize `PlaceholderText` at line 316 of Split.cpp. 

My coding ability is very limited so i don't know if it is me or the new committed changes, but i'm very doubtful of the latter, since ubuntu-latest build passed. I think i'm dank.

**Comment by ZoeS17** [comment]
@bennyhillthebest  I think the code in `Modes.cpp` is looking for a raw file named modes, at wherever Chatterino is run from. and looking to see if it contains `nightly` on a single line.

**Comment by pajlada** [comment]
Modes are normally part of a Chatterino installation - for example, for the portable installation there will be a file called modes next to the Chatterino application file indicating to it that it should look for settings in the current folder instead of in the operating systems "AppData" folder.

To forcefully add/remove a mode, you would need create (or edit if the file already exists) the `modes` file in the same folder as the Chatterino application file exists. For example, this could be in `/usr/bin` or `/usr/local/bin` if you have installed chatterino using `make install`. What you would do then is `sudo vim /usr/local/modes` and add the line `nightly` to the file.

The reason this process seems a bit weird is because this is kind of a misuse of the modes functionality - it's really there for development-like flags but I think in your case that fits.

**Comment by bennyhillthebest** [comment]
Sorry to necrobump this issue, but i have a doubt: if i use the x86_64 AppImage is it possible to insert in some way the modes file? I would think not, since Chatterino is mounted in /tmp/ under a slightly different folder every time, but i would like to have confirmation, thank you very much

**Comment by ZoeS17** [comment]
@bennyhillthebest Seems you can run `./Chatterino-x86_64.AppImage` with the directory `Chatterino-x86_64.AppImage.home` in the same folder as the AppImage and it will let you just drop the `modes` file there, or you can run the AppImage with `--appimage-portable-home`. I just ran `./Chatterino-x86_64.AppImage --appimage-help` for some handy output. Hope it helps.

**Comment by bennyhillthebest** [comment]
I tried using the .config and the .home folder, but they don't work, which is probably to be expected since the modes file needs to be in the same path as the binary, but thank you nonetheless @ZoeS17 because now i know that i can --appimage-extract and insert into squashfs-root/usr the modes files
