### ISSUE TITLE
Emote issue

### ISSUE THREAD

**Issue by sianisdead** [Chatterino/chatterino2#2197]
Every channel that has subscription emotes shows the message: "no subscription emotes available"

![Capture](https://user-images.githubusercontent.com/74604166/99394198-63f44f80-28d6-11eb-8622-69e5286d772f.PNG)

Chatterino 2.2.2-fix (commit a82f57f94)
Windows 10

**Comment by Felanbird** [comment]
This tab is not for showing a channels subscriber emotes, it's for showing your own sub/global emotes. You're receiving this error because you are either,
* Not Logged in
* Have no subscriber/global emotes

**Comment by sianisdead** [comment]
It appears as though it is inconsistent or a bug from the result of an update I had for the app today. I was both signed in and had a page open with emotes and my account is subscribed to quite a few other streamers. Upon opening and reopening the app a few times, it fixed itself but the other tabs (channel/global/emojis) were always fine, it was just the Subs channel that was appearing to not show for quite a while, even when logged in to a subscribed account.

![image](https://user-images.githubusercontent.com/74604166/99427403-49819c80-28fd-11eb-8bfe-49d7b1b192ec.png)

**Comment by alazymeme** [comment]
Cannot reproduce | Windows 10 | commit 529f19a2d

**Comment by apa420** [comment]
Api call might fail to fetch emotes so it drops the try, maybe add a feature that retries fetching emotes?

**Comment by zneix** [comment]
With the recent update (v2.3.3 or [latest nightly](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build)) fetching emoteset data from Twitch API instead of our servers this should eliminate a potential failure. If the issue keeps occurring feel free to @mention me and I'll reopen the issue.

**Comment by ltindel2021** [comment]
@zneix Hello, I hope you are doing well! I recently found this thread, and was wondering if there was any solution to this issue because I am currently having the same problem with chatterino. I have the latest version, and Chatterino was working fine earlier, but for some reason it is not working with the subscription emotes. It is telling me there are none when there are, and I'm subscribed to three other streamers.

**Comment by Felanbird** [comment]
@ltindel2021 As stated in the last comment, we get our data directly from Twitch now, so just restart or wait it out basically as it's likely to be an issue between your ISP and Twitch, or Twitch themselves.

**Comment by ltindel2021** [comment]
@Felanbird Thank you! I did a bit of information searching to see if it was a visual studios issue or a shortcut issue. For some reason it works now, but I have to open the emotes box 2 times for it to start working. I think Chatterino or Twitch is just having a moment. Thank you again :).
