### ISSUE TITLE
commands not saving

### ISSUE THREAD

**Issue by yfreezer** [Chatterino/chatterino2#2222]
everytime i relaunch my chatterino, all my commands are gone

**Comment by alazymeme** [comment]
Hello yfreezer

When you create an issue and select "Bug Report", you will be presented with a template to input your issue, etc. Please kindly either:

1. Edit your issue with the necessary template; or
2. Close this issue and open a new issue with the aforementioned template.

This template is intentionally used in order to assist with diagnosis of your issue and potentially fixing it.

Kind Regards
ALazyMeme

**Comment by zneix** [comment]
@yfreezer There was an issue with commands not saving and it was fixed in the PR #2016, please make sure you're     running version that has mentioned fix or newer.

**Comment by apa420** [comment]
Check that the commands.json file is NOT in read-only mode. If the issue persists please reopen the issue.
