### ISSUE TITLE
Search for channels in /mentions tab

### ISSUE THREAD

**Issue by VulpesHD** [Chatterino/chatterino2#2299]
Give us the ability to search for specific channels in the mentions tab: #channelname
(When I get mentioned in a lot of random channels and I only want to search for specific ones out of the mix, I have no easy way of doing it)
CTRL + F => #channelname

**Comment by talneoran** [comment]
Is there anyone working on this atm? If not I can be assigned to it assuming it's deemed as something worth adding.
I suggest the addition of a search predicate "in:{channel}", that will filter messages according to the channel they were sent in.
Example: 
![image](https://user-images.githubusercontent.com/43518924/114323053-151cb000-9b2c-11eb-9dc7-a6916f3fcfab.png)
This also supports multiple channels separated by comma, and can be combined with other existing predicates, similar to how the "from:{user}" predicate works.
Currently the way I have it working, is the predicate can be applied wherever (not just in mentions tab), but it's pretty much useless outside of /mentions (due to there only being one possibility for the channel), and I'm not sure if there's a point in enforcing it only being useable in /mentions.
