### ISSUE TITLE
GlitchCon emotes should be grouped into one single group

### ISSUE THREAD

**Issue by Trung0246** [Chatterino/chatterino2#2341]
Currently emotes earned through GlitchCon (2.2.2-fix) are being displayed like this (as if they are separate groups):

![image](https://user-images.githubusercontent.com/11626920/103724993-7ad82980-4f8a-11eb-8a6d-d0cce704828b.png)

Is it possible to group them into a single group like those holiday emotes and lgbt+ emotes?

**Comment by leon-richardt** [comment]
The grouping is determined by relying on the emote set information provided by Twitch. Although it seems reasonable that the GlitchCon emotes should be in the same emote set, this doesn't seem to be the case.
In order to group them anyway, we would need to manually override the emote set value for specific emotes.

**Comment by zneix** [comment]
> as if they are separate groups

well... they are. As Leon has already mentioned, those are in separate emote sets.
To solve this "issue", we would have to hard-code emote set IDs, but such solution just feels... wrong.

**Comment by zneix** [comment]
As suggested in https://github.com/Chatterino/chatterino2/issues/2954#issuecomment-873585576 I could consider adding another section / tab for twitch's seasonal emotes. It sounds like a good concept, but has to be made well.

> Put seasonal/event emotes in a seperate tab in the emote menu as they aren't sub emotes after all.
