### ISSUE TITLE
Cannot move window via top bar or resize window after clicking the add account button

### ISSUE THREAD

**Issue by ALazyMeme** [Chatterino/chatterino2#2378]
**Describe the bug**
After clicking the add account button, you cannot move the window using the top bar or resize using the edge of the application

**To reproduce**
1. Click and drag the window using the top bar, notice it works normally
2. Go to settings to add account, click add account
3. Close the window, close the settings

**Screenshots**

https://user-images.githubusercontent.com/41973452/160349134-e34508d1-20dd-4550-8212-b6bf956e0f43.mp4

**Chatterino version**
commit a9b1af60d

**Operating system**
Windows 10

**Comment by Torston420** [comment]
Can reproduce on Windows 10 1909

**Comment by ZerOmNia** [comment]
Still seeing this. Have to relaunch the app to reset it. Windows 10 21H2

**Comment by jaerockets** [comment]
same issue here, luckily closing and reopening fixes it

**Comment by PurplProto** [comment]
Still able to repo this:
Chatterino 2.3.5 (commit 81a62764c)
Windows 10 21H2

**Comment by derossm** [comment]
Still reproducible with commit 81a62764c
Windows 11

**Comment by Felanbird** [comment]
> Still reproducible with commit [81a6276](https://github.com/Chatterino/chatterino2/commit/81a62764c866a878846ef8917814c416de1fe47e) 

That's why the issue is still open

**Comment by derossm** [comment]
> > Still reproducible with commit [81a6276](https://github.com/Chatterino/chatterino2/commit/81a62764c866a878846ef8917814c416de1fe47e)
> 
> That's why the issue is still open edit: Also that commit is from April so even if we had fixed it you wouldn't have the fix.

This is fixed in https://github.com/Chatterino/chatterino2/pull/3636/commits/e269a75c1bd2e5d77e923c423711d49a1115c6a4 but was closed without being approved.

Using platform specific calls to lock Qt windows is less than ideal, and the original purpose is dubious, so just removing this macro qualified windows api call makes sense. The account panel is already "always on top" relative other chatterino windows while open, so being able to move or resize a window behind it doesn't seem like a benefit nor does it seem to pose any security risk to allow it to be moved afaik.

I might suggest disabling chat input while account panel is open to avoid accidental pastes to chat, but that is unrelated and not affected by this issue or fix.

Otherwise you probably have to fully redraw the main window to fix it; just calling ::SetWindowPos without the flags won't reset the permissions.

**Comment by jammehcow** [comment]
@derossm the reason why that PR wasn't merged is because it causes issues with chatterino's "Always On Top" setting when enabled. It really does require a call to some Windows shit just to prevent that from being an issue. If you wanna take a crack at fixing it be my guest - I haven't had the incentive to fix it as I don't use Windows.
