### ISSUE TITLE
Cheer emotes don't have feature parity with BTTV emotes.

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#2434]
**Describe the bug**

Cheer emotes (Cheer1, Cheer10, pajaCheer1, etc.) cannot be zoomed in. You cannot open links to the GIF.

**To reproduce**

 1. Find a channel with people cheering.
 2. Hover over the cheer emote and see that it doesn't have a preview.
 3. Right click the emote and see that you cannot open the link in a browser.

**Screenshots**

N/A

**Chatterino version**

Chatterino + Dankerino patches 763acf9a based on upstream c2782666a66810ef6b973ce543626ad80d07e352

**Operating system**

Ubuntu 20.04.1 LTS (Focal Fossa)

**Additional information**

**Comment by jammehcow** [comment]
This is caused by the `EmoteElement` created for a bit cheer not having a valid `Tooltip` set when it's created. This means it fails the check in [ChannelView.cpp#L1406](https://github.com/Chatterino/chatterino2/blob/master/src/widgets/helper/ChannelView.cpp#L1406) where the tooltip must not be empty.
