### ISSUE TITLE
Filters are not working

### ISSUE THREAD

**Issue by ALazyMeme** [Chatterino/chatterino2#2466]
**Describe the bug**
I'm currently trying to test either of the below filters:

`(author.name) != ("user1" || "user2")`
or
`(author.name) != (r"(user1|user2)")`
or
`(author.name) != "user1" || "user2"`
or
`author.name != r"(user1|user2)"`

None of which are filtering out the messages from either user.

**To reproduce**
1. Create a filter as mentioned above
2. Set the filter
3. Notice it doesn't work

**Screenshots**
![image](https://user-images.githubusercontent.com/12804673/108580455-40c6b980-7377-11eb-9916-c84ed4d6557e.png)

![image](https://user-images.githubusercontent.com/12804673/108580471-550ab680-7377-11eb-85cd-c0f6696e7fbf.png)

![image](https://user-images.githubusercontent.com/12804673/108580487-6653c300-7377-11eb-9db6-a4a3daaa5b4b.png)

![image](https://user-images.githubusercontent.com/12804673/108580560-b6328a00-7377-11eb-946c-55128dbac9f0.png)

**Chatterino version**
Nightly 2.2.3-beta2 (commit 7d9f4c2b0, )

**Operating system**
Windows 10

**Comment by alazymeme** [comment]
The only way I got it working was using `author.name != "scriptorex" && author.name != "pajbot"`

Which doesn't really seem efficient...

**Comment by leon-richardt** [comment]
> The only way I got it working was using `author.name != "scriptorex" && author.name != "pajbot"`

In contrast to the examples in the main post, this seems like the only instance which actually uses correct syntax for filters. (At least as far as I can tell from the wiki page on filters.) So no surprise it would work. Without having looked at the expression parsing/logic too much, I would _strongly_ suspect that the `||` operator only works on booleans, not on strings.

As per the [wiki](https://wiki.chatterino.com/Filters/#regular-expressions), if you want to use regular expressions, you would need to use the `match` keyword instead of the `!=` operator. I suppose your expression could be simplified using the list literal.

There is an argument to be made that the parser could be improved to detect more operator/type mismatches, although I can't comment on how difficult that would be in practive.

**Comment by alazymeme** [comment]
I think overall the documentation needs to be better worded, the way it currently is; is causing quite a bit of confusion.

**Comment by the-sloth** [comment]
Quite a few problems with filters; for one, "match" is an unknown operator. Even the examples give errors

**Comment by the-sloth** [comment]
> 
> 
> Quite a few problems with filters; for one, "match" is an unknown operator. Even the examples give errors

Works on nightly versions. As described here: https://github.com/Chatterino/chatterino2/issues/2455#issuecomment-784483435

**Comment by nilyt** [comment]
Additionally, I can't find a way to negate the `contains`, `startswith` or `endswith` operators.
The only "valid" syntax I could come up with is the following, but that doesn't seem to work.
```
! (message.content startswith ("!gamble" || "!command"))
```
Any way to make that one work?

**Comment by zneix** [comment]
@nilyt I believe support for regex in Filters has been merged in ages ago (a.k.a. in #2225), try updating to [latest nightly](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build).

@dnsge Would it be possible for you to get something like what @nilyt explained in the comment above working?

@alazymeme would regex support be enough for you for now or do we have to keep this issue open?

**Comment by dnsge** [comment]
> @dnsge Would it be possible for you to get something like what @nilyt explained in the comment above working?

I think a filter equivalent to the boolean operations in @nilyt's edit would look like this with a regex:

 `!(message.content match r"^(!gamble|!command)")`

(I'm no regex wizard but I think this is the best way to write it)
