### ISSUE TITLE
Specifying channel via command-line argument disables all settings saving

### ISSUE THREAD

**Issue by sPOiDar** [Chatterino/chatterino2#2484]
**Describe the bug**
When specifying a channel to join via the CLI argument, changes to any settings are not persisted.

**To reproduce**
- Start chatterino with `--channels` argument.
- Change any settings (including authorizing via OAUTH2).
- Close and re-open chatterino,, note that any changed settings have reverted to last launch.

**Chatterino version**
Chatterino 2.2.3-beta2 (commit 4a5347221)

**Operating system**
Linux (Arch)

**Comment by leon-richardt** [comment]
> * Start chatterino with `--join` argument.

I'm assuming you mean `--channels`.

What you describe is not a bug but intended behavior (although we can argue whether it's _sensible_ behavior). See discussion in https://github.com/Chatterino/chatterino2/pull/1940 for more background on this decision.

**Comment by sPOiDar** [comment]
> I'm assuming you mean `--channels`.

Apologies, yes, I meant `--channels`, edited the original report to reflect this.

> What you describe is not a bug but intended behavior (although we can argue whether it's sensible behavior). See discussion in #1940 for more background on this decision.

I don't see the rationale for this decision there, the decision seems to be based on https://github.com/Chatterino/chatterino2/pull/1940#issuecomment-687637127 which does not provide anything in the way of details as to why this might be a good idea.

This is really awkward and unintuitive behaviour, especially in the case that refresh of an access token is required, as the new token is never saved, provided chatterino is always launched with `--channels`. But even outside that case, I'd suggest that blanket non-saving of settings is never the expected/desired behaviour for users.

**Comment by leon-richardt** [comment]
> I don't see the rationale for this decision there, the decision seems to be based on [#1940 (comment)](https://github.com/Chatterino/chatterino2/pull/1940#issuecomment-687637127) which does not provide anything in the way of details as to why this might be a good idea.

I think the problem stems from "how the feature was originally intended" vs. "how the feature is used".

---

Quoting https://github.com/Chatterino/chatterino2/pull/1940#issuecomment-687633028:
> I suppose this should also disable settings from being changed and saved since they are not synced between instances?

If the typical use case is using `--channels` to start a second Chatterino instance in addition to one you already have opened, not saving settings in one of them is reasonable behavior. This is because settings are not synced between instances (as @fourtf noted in the quoted comment); meaning that the settings from the instance that is closed last would always **override** any setting changes you may have performed in a different instance.

If the typical use case is what you describe (always starting Chatterino with `--channels`), the behavior seems unreasonable and unintuitive.

---

Either way, it is a good opportunity to discuss what the "assumed use case" should be, and brainstorm potential solutions.

**Comment by sPOiDar** [comment]
> This is because settings are not synced between instances (as @fourtf noted in the quoted comment); meaning that the settings from the instance that is closed last would always override any setting changes you may have performed in a different instance.

This occurs if, and only if, both instances modify settings while they're open, correct? And wouldn't this apply no matter how you start multiple instances? Special-casing launch with `--channels` seems off, if that's the case. I suppose it might be possible to watch configs for modification and refresh the local state when they change, no idea how invasive that would be.

> If the typical use case is what you describe (always starting Chatterino with `--channels`)

One use-case for the addition of this flag is for use with applications like Streamlink. If that's how users launch chatterino, they're unlikely to ever launch without the `--channels` flag. I'm not certain what the use-case might be other than calling from some sort of wrapper, or other automation.

---

While we're hashing this out, I'd love to see either an `--existing-window` flag that just opens a tab in an existing window (or opens a window if one doesn't exist), or for that to be the default when calling with `--channels`, and a `--new-window` flag added to cause the current behaviour if that's desirable. This would need some sort of socket or something for communication though, so I understand why it wasn't included initially.

**Comment by leon-richardt** [comment]
> This occurs if, and only if, both instances modify settings while they're open, correct? And wouldn't this apply no matter how you start multiple instances?

Yes to both. I assume the special case for `--channels` exists because it's easy to detect, but it really is just an assumption. @fourtf and @pajlada may be able to shed more light onto this.


> I suppose it might be possible to watch configs for modification and refresh the local state when they change, no idea how invasive that would be.

Possible? Sure. But it would require a good chunk of work someone would have to do. (That would probably need to happen in [pajlada/settings](https://github.com/pajlada/settings), which is what we use for settings management.)

---

> While we're hashing this out, I'd love to see either an `--existing-window` flag that just opens a tab in an existing window (or opens a window if one doesn't exist), or for that to be the default when calling with `--channels`, and a `--new-window` flag added to cause the current behaviour if that's desirable.

It'd probably be best to open a separate issue for this so we can keep the discussion focused. I understand there is demand for this, see e.g. https://github.com/Chatterino/chatterino2/discussions/2460 and https://github.com/streamlink/streamlink-twitch-gui/issues/607.

**Comment by pajlada** [comment]
Not something we're planning right now, but feel free to re-open this and I'll convert it into a discussion instead to gather more feedback
