### ISSUE TITLE
Highlight Users with a Mod Comment

### ISSUE THREAD

**Issue by simon-crsshr** [Chatterino/chatterino2#2526]
It would be cool to have a feature to highlight users which have a mod comment.

It would be really usefull for mods, so they can instantly see which users have a mod comment.

**Comment by Felanbird** [comment]
While this feature could be useful, it has 2 problems.

1. As far as I'm aware there is currently no API for mod comments so that automatically makes it impossible.
2. If the API did exist, this would require querying the API for every single user who ever types any message, which would be an extreme and unreasonable amount of requests.
