### ISSUE TITLE
`/setgame` enhancement

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#2599]
**What should be added?**
The `/setgame` command should use the search categories helix endpoint prior to setting the game: https://dev.twitch.tv/docs/api/reference#search-categories

**Why should it be added?**
Searching for the game in twitch's db allows for a much more "loose" way of setting a game. Easiest example I can think of is "the divison 2". It's not the full game name and it isn't capitalized at all. However twitch's category search endpoint will allow for a much more "loose" search for a game. Refer below:

![image](https://user-images.githubusercontent.com/12804673/113867897-6d814400-97f2-11eb-87b6-3f9dba1f04da.png)

We can easily use the ID from the resulting search to set the game. This will result in 2 API requests being made, but a far better experience for the user. Under the scenario where multiple games are returned from the endpoint, we should use the first entry.

**Comment by pajlada** [comment]
This is a pretty decent first issue for someone wanting to contribute to Chatterino2.

It consists of two parts:
1) Update `src/providers/twitch/api/Helix.{hpp,cpp}` to support the [**Search Categories**](https://dev.twitch.tv/docs/api/reference#search-categories) endpoint.
2) Update `src/controllers/commands/CommandController.cpp` to use the newly implemented **Search Categories** endpoint instead of `fetchGames`

**Comment by Yoitsu** [comment]
Done this already, doing PR atm

**Comment by pajlada** [comment]
Closed by #2609
