### ISSUE TITLE
Not all users with gray names get colorized, while "Colorize users without color set (gray names)" is enabled

### ISSUE THREAD

**Issue by karl-police** [Chatterino/chatterino2#2644]
**Describe the bug**
Not all users with gray names get colorized, while "Colorize users without color set (gray names)" is enabled. Or am I missing something? Also, is that option new?

Example:
![](https://i.imgur.com/WzHWZWJ.png)

**To reproduce**
Find someone \*shrug\* or make an alt account and let it type maybe.

**Chatterino version**
Chatterino 2.3.0 (commit 58017a754)

**Operating system**
Windows 10 64-Bit

**Comment by jammehcow** [comment]
1. The user might have their colour manually set to gray
 2. Gray could be one of the colours chosen from as a random pick

Can look into this later today

**Comment by Felanbird** [comment]
The user in question is using `#4C4A4A` which is a gray color. 

The point of the setting is to change the color of people who have never chosen a color, which causes them to return no color information, so Chatterino labeled these users as "graynames". People who have chosen gray colors for their names are unaffected.

Also Chatterino uses color normalization so you are likely to see all kinds of gray hex's show up as the same gray visually.

**Comment by zneix** [comment]
Just as Felanbird explained, the user you've shown is not a greyname - a greyname is a user, who has never set their color - "beent0jailmate" has set it, it's just a coincidence that he set it to grey, thus this is not a Chatterino issue.

And to answer your question:

> Also, is that option new?

Yes, this is quite recent. Option has been a part of nightly builds for some time (since 18th Oct 2020) but 2.3.0 is the first stable release with filters support.

**Comment by karl-police** [comment]
ah, I think everyone calling it "gray names" confused me

I forgot that there is an option that allows them to return to no color.
