### ISSUE TITLE
Search Predicate for Disabled Messages

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/chatterino2#2653]
**What should be added?**
Add a search predicate for disabled messages (i.e., messages that were removed by a timeout). This predicate should simply check for the `MessageFlag::Disabled` flag.
Suggested syntax: `is:disabled`. Open to other suggestions though.

**Why should it be added?**
Allows you to quickly check automatically timed out messages, e.g. to see if they warrant a longer timeout or permanent ban or to copy that dank new ASCII copypasta.

This feature should be "almost free" in regards to additional code complexity and does not harm the current user experience.

**Comment by talneoran** [comment]
Seems useful to me, but maybe `is:deleted` could be better since I think that's what people usually know removed messages by (and that's the name for them in BTTV and FFZ).
Also, maybe this can be part of a general search predicate that checks for various message flags/properties. A few other options that come to mind are timeout messages, subcriptions, highlighted messages, etc.

**Comment by leon-richardt** [comment]
Agree on all counts 👍
