### ISSUE TITLE
Clickable Badges

### ISSUE THREAD

**Issue by AustinHolderr** [Chatterino/chatterino2#2654]
# **What should be added?** #

### **Clickable Badges...** ###
Clickable Badges such as those that can be found clickable in the native Twitch chat client should be added to Chatterino.

# **Why should it be added?** #

I believe this should be added because it would be very helpful to be able to click on the Prime Gaming (for example) and go right to the link from there, or the Twitch Staff Badge, FFZ Supporter, Twitch Turbo, Verified (Partner) Badge, VIP, etc.

**Comment by AustinHolderr** [comment]
If you need clarification regarding what I'm talking about here, let me know.

**Comment by jammehcow** [comment]
I personally wouldn't want this functionality so maybe (if implemented) it would be worth adding a setting to toggle it off?

**Comment by AustinHolderr** [comment]
> I personally wouldn't want this functionality so maybe (if implemented) it would be worth adding a setting to toggle it off?

possibly

**Comment by zneix** [comment]
If we were to click a badge, what would it even do? Some special popout with badge description would open or what is gonna happen? Please describe this a little bit more to someone, who never uses webchat.

**Comment by gempir** [comment]
Adding "features" because web chat has them isn't the goal of Chatterino. Chatterino is supposed to offer a more refined experience than webchat.

Personally I see little benefit to clickable badges. The one use case you present is being able to click to prime gaming, which I find barely useful and I would be more annoyed when clicking on accident and then a random web page opens.

I think you should elaborate on other use cases where clickable badges are actually helpful for users.

**Comment by alazymeme** [comment]
I don't see any reason to add this, and adding more settings really isn't a good idea given the current state of the settings menu.

**Comment by AustinHolderr** [comment]
i mean if you all think it's not a good idea, i'll just close this..

**Comment by AustinHolderr** [comment]
i mean if you all think it's not a good idea, i'll just close this..

**Comment by pajlada** [comment]
Related to #2667 and #2663 

Might solve your issue
