### ISSUE TITLE
Blocking Usernames restarts when I reopen Chatterino, any possible solutions or workaround 

### ISSUE THREAD

**Issue by itzfinn** [Chatterino/chatterino2#2687]
Ignore Tab -> User 

**Describe the bug**
 This issue is whenever I block a username, I don't see the username ever, nor there respond or phrases of whatnot. I updated to the Chatterino 2.3.0 , and when I block a user and close the the program and reopen and say watch a livestream and I block that said user last time , I see that msg again. Not only that but I see a huge list of nothing on top of the usernames I can see, but I do see the other usernames I blocked Chatterino registered in the Ignored tab "Username". This has been an constant thing back and forth and I don't want this to do this again and again. On previous version the program was able to capture the block list from the Twitch account, but this version can't catch them all :/

**To reproduce**
 Retrieve a certain string of code or information from previous version and make it so users who use this won't redo and re block the same person over and over again even when the stream is offline or online 

**Screenshots**

![chatterinobugissue](https://user-images.githubusercontent.com/83194957/116020508-0645fb00-a60c-11eb-8639-ab58b5351bf6.PNG)

**Chatterino version**
 Chatterino 2.3.0 (commit 58017a754)

**Operating system**
  Windows 10 64bit v20H2 

**Additional information**

**Comment by Felanbird** [comment]
This was probably never actually the block list resetting, but just failing to load your blocks from Twitch. 

As this issue is ancient and we recently updated block-list-loading, this shouldn't happen on versions after fca57696bba18943ac4295892daf803eb72f4db9 (as of writing this comment only the [nightly build](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build) has this change, but 2.4.5 onwards will)
