### ISSUE TITLE
[Caching] Remove cache items after a period of time

### ISSUE THREAD

**Issue by jammehcow** [Chatterino/chatterino2#2700]
**What should be added?**
Emotes (and by extensions other cache items) should be removed from storage after a set period of time (14 or 30 days sounds reasonable).

**Why should it be added?**
This change would reduce the disk presence of Chatterino considerably - especially for users who have used the same installation for a long period of time and subsequently racked up a large set of cached emotes.

**Comment by pajlada** [comment]
As per the `clearCache` function in `src/RunGui.cpp` https://github.com/Chatterino/chatterino2/blob/master/src/RunGui.cpp#L146-L159 we intend to clear cache that hasn't been modified in 14 days.

This function is run one minute after Chatterino startup here https://github.com/Chatterino/chatterino2/blob/master/src/RunGui.cpp#L190-L194

**Comment by fourtf** [comment]
I understand that with the issue templates we have it is reasonable to try and come up with a solution instead of describing a problem. This is why here the actual issue (cache too big) is lost in translation. Funnily enough the suggested solution is already in place, which is why I'll close this issue. For the actual issue I think that the cache is reasonable as it saves network resources and at least my cache has a pretty reasonable size (~100mb).
