### ISSUE TITLE
Badge Layout 

### ISSUE THREAD

**Issue by DWURN** [Chatterino/chatterino2#2715]
**Why should it be added?**

Swapping the Chatterino Support badge as well as the FFZ badges to the left side of the sub and vanity badges.

Having those badges on the far right break up users sub/vanity badge to name color aesthetic [example](https://gyazo.com/08279fdb69c5d26676a7d684e7d6e84c)

______________________________________________________________________________________

**What should be added?**

An option to hide your own chatterino supporter badge.

Some people might have wanted to support but don't enjoy the appeal of the badge/aesthetic in conjunction with their other badges

**Comment by alazymeme** [comment]
I apologise, I'm failing to see how this will be useful in Chatterino.

Could you please further advise as to how fixing your name/badge aesthetic will benefit 90%+ of the Chatterino users?

**Comment by alazymeme** [comment]
DM with fourtf:

![image](https://user-images.githubusercontent.com/12804673/116525517-f08e4980-a91b-11eb-99a6-f981f9139f33.png)

**Comment by pajlada** [comment]
> An option to hide your own chatterino supporter badge.

You can disable all Chatterino badges in your Chatterino by opening Settings, scrolling down to the **Visible badges** section and unchecking Chatterino. Would this solve your issue?

 > Swapping the Chatterino Support badge as well as the FFZ badges to the left side of the sub and vanity badges.

We will not add an option to modify the badge order at runtime. However, the badge order is not something set in stone so if you are interested in modifying the badge order please [create a Discussion](https://github.com/Chatterino/chatterino2/discussions/new) about it to gather feedback.
For reference, the current badge order is:
Twitch Predictions (temporary badges during Predictions) -> Twitch Global Authority (e.g. Staff or Admin badge) -> Twitch Channel Authority (e.g. Broadcaster, Moderator, VIP), Twitch Channel Subscriber, Twitch Vanity (e.g. prime, bits, subgift badge), Chatterino (Support badge, developer badge), FrankerFaceZ badge (Bot badge, FrankerFaceZ supporter/developer).

As for disabling your own Chatterino badge, which is the option that @alazymeme came up with for you in the previous comment, if that's something you think solves your issue please considering opening an issue on the [website repo](https://github.com/Chatterino/website) instead of here, as it doesn't really pertain to the Chatterino application.

**Comment by fourtf** [comment]
The service for the badge is something I track on my own, no ticket needed. Furthermore the comment by @pajlada seems to close resolve this conversation.
