### ISSUE TITLE
Showing Streamlabs donations in Chatterino

### ISSUE THREAD

**Issue by HuBaX** [Chatterino/chatterino2#2762]
Many streamers are managing their donations with Streamlabs. Is it possible to show the latest Streamlabs donations in Chatterino?

I've seen that the Streamlabs API provides an endpoint: https://dev.streamlabs.com/reference#donations

**Comment by leon-richardt** [comment]
So the idea would be to poll for new donations periodically?

**Comment by Mm2PL** [comment]
This idea looks better suited for a chat bot rather than a chat client, however I understand the appeal of having it in a chat client. Furthermore this requires having a Streamlabs access token which has to be created and stored somehow. The first idea I had about this feature is that viewers could also see a donation appear in the chat but it appears that the API doesn't allow for this kind of a use case.

**Comment by HuBaX** [comment]
I thought of it being a streamers only feature. Fetching the donations periodically is the only possibility I see here.

**Comment by apa420** [comment]
Doesn't streamlabs already have their own bot that can do this.
Also doesn't streamlabs have a application just for donations already?
I don't see what chatterino could bring to the table that these two options can't.
It's a pretty big feature and to me it seems overkill to implement it in chatterino.

**Comment by fourtf** [comment]
out of scope; I would rather see a proper standalone app made by someone else than a half asses implementation in Chatterino
