### ISSUE TITLE
Re-add the enhancement template.

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#2797]
**What should be added?**

We used to have a template for enhancements, which was unfortunately removed during the bug-template overhaul in #2724 
I believe this should be re-added, (or at least something similar).

**Why should it be added?**

Without some form of structure, many enhancement suggestions will be missing key feature ideas/generalized wording to help contributors understand what the person opening the suggestion, actually wants from their suggestion.

**Screenshot(s)**

\<!-- A clear and concise description of what motivates you to request this change. --\>

https://i.imgur.com/HOpmc9r.png
☝️ Stick figure drawing depicting my motivation for this change

**Comment by fourtf** [comment]
> We used to have a template for enhancements, which was unfortunately removed during the bug-template overhaul in #2724

The enhancement template was removed for a reason. This passive aggressive "unfortunately" shit doesn't help the case.

> Without some form of structure, many enhancement suggestions will be missing key feature ideas/generalized wording to help contributors understand what the person opening the suggestion, actually wants from their suggestion.

The point is that the person who makes an issue request doesn't know how it should be implemented and can't properly put it into context. Having people who do not have developing experience come up with a solution themselves ("what should be added") and then having them argue for that solution ("why should it be added") causes their actual issue to get lost in translation.

Not focusing on the underlying issue also makes it hard to evaluate the importance of it. But if you knew the actual issue then there is an opportunity to find a better solution for the problem. This issue is also an example for this. It suggests that bringing back the enhancement request fixes people being unable to communicate their concerns when this seems more like a report that one specific post was hard to understand and ignored the template.

> **Screenshot(s)**
> 
> https://i.imgur.com/HOpmc9r.png
> ☝️ Stick figure drawing depicting my motivation for this change

I find it dubious to think that the enhancement template would have gotten a better here since the other template was straight up ignored.

**Comment by Felanbird** [comment]
While your other arguments are fair, I disagree with this part.

> I find it dubious to think that the enhancement template would have gotten a better here since the other template was straight up ignored.
![image](https://user-images.githubusercontent.com/41973452/118991318-a19f6700-b951-11eb-8a52-2087fc110649.png)

Currently this is how users currently see the issue reporting

1. Is my issue a bug? no? Alright I'll move down
2. Is my issue related to the browser extension? no? Alright I'll move down
3. Neither of these 2 options apply to me, I better open a blank issue.

I wouldn't classify following the steps, exactly as they are laid out, "ignoring" the template. 

If anything we need to re-word the first option, so people at least utilize that for opening their enhancements.

**Comment by fourtf** [comment]
I feel like getting the name of the template right is kinda tricky. It needs to incentivize people to use it and at the same time not fall into the normal "feature request" category.

**Comment by jammehcow** [comment]
As someone who chose opt. 3 recently due to it not fitting under the other two, a rename would be ideal.
Maybe the word 'refinement' could be used? Implies a change to something that already exists.

**Comment by fourtf** [comment]
Closing since the enhancement template isn't getting readded
