### ISSUE TITLE
Message disappeared while someone else banned a user

### ISSUE THREAD

**Issue by hendriklhf** [Chatterino/chatterino2#2804]
My message disappeared while someone else was banning a user.
I saw my message for a maximum of 0.5sec and then it just disappeared as the notification of the banned user "benastroworld" showed up approximately at the same time as my message showed up. The other user was still able to see my message.

My message not visible in chat:
![grafik](https://user-images.githubusercontent.com/73221731/119209516-58612b80-baa7-11eb-8503-81f5f95ff598.png)
My message visible in the logs:
![grafik](https://user-images.githubusercontent.com/73221731/119209567-99594000-baa7-11eb-8a97-cce60472aed7.png)

Windows 10, Chatterino Nightly 2.3.2 ([ddba279ff](https://github.com/Chatterino/chatterino2/commit/ddba279ff))

**Comment by Felanbird** [comment]
@Sterbehilfe had you recently account switched or disconnected? Might be related to an issue I reported externally about reconnect messages overriding chat messages, or at least the same concept.

**Comment by Sterbehilfe** [comment]
No, no recent account switches or disconnects.

**Comment by Felanbird** [comment]
Ah, well as a note I have encountered this issue once before, but I was unable to consistently replicate it.
![image](https://user-images.githubusercontent.com/41973452/119214781-660eb500-ba97-11eb-8b7f-c58cc0f36813.png)

**Comment by Sterbehilfe** [comment]
Yeah, I can imagine it's quite difficult to replicate it, but looks like what happend to me.

**Comment by LosFarmosCTL** [comment]
Happens pretty often for me as well, usually with automated timeouts from bots that send multiple TOs in quick succession (i.e. ohbot).

Don't know how to consistently replicate it either though :/

**Comment by Mm2PL** [comment]
I believe this is a race condition while updating the IRC timeout message with the PubSub one.
When the pubsub message is received `Channel::addOrReplaceTimeout()` ( https://github.com/Chatterino/chatterino2/blob/master/src/common/Channel.cpp#L99 ) is called.  Then inside of that function `Channel::replaceMessage(MessagePtr old, MessagePtr new)` is called which in turn calls `Channel::replaceMessage(size_t index, MessagePtr replacement)` which replaces a bad message because `Channel::messages_` was modified sometime in this whole process.
At least that's what I think is happening. ![WAYTOODANK](https://cdn.betterttv.net/emote/5ad22a7096065b6c6bddf7f3/1x)

**Comment by Felanbird** [comment]
This might be expected behavior, but I accidentally just noticed the "missing" message still shows up in the usercard history.
![image](https://user-images.githubusercontent.com/41973452/131457231-262c6181-028b-4005-9795-22c4b2b4bcb2.png)

**Comment by karl-police** [comment]
> I believe this is a race condition while updating the IRC timeout message with the PubSub one. When the pubsub message is received `Channel::addOrReplaceTimeout()` ( https://github.com/Chatterino/chatterino2/blob/master/src/common/Channel.cpp#L99 ) is called. Then inside of that function `Channel::replaceMessage(MessagePtr old, MessagePtr new)` ( https://github.com/Chatterino/chatterino2/blob/master/src/common/Channel.cpp#L223 ) is called which in turn calls `Channel::replaceMessage(size_t index, MessagePtr replacement)` ( https://github.com/Chatterino/chatterino2/blob/master/src/common/Channel.cpp#L233 ) (via a signal) which replaces a bad message because `Channel::messages_` was modified sometime in this whole process. At least that's what I think is happening. ![WAYTOODANK](https://camo.githubusercontent.com/cc3808cffcbc0a6ad6884e379cb82d03b8a3ee9432581a26b8fe5c120316296e/68747470733a2f2f63646e2e6265747465727474762e6e65742f656d6f74652f3561643232613730393630363562366336626464663766332f3178). @pajlada, can I have your input on this?

So this function adds a message if it does not exist, or replaces it?

But in the meantime while it doesn't exist, won't it just create a new one from the IRC or whatever anyways?

**Comment by LosFarmosCTL** [comment]
I discovered some new information about this today, thought I might as well document that here.

For one, this is not directly related to PubSub messages, this can also happen when timeouts get grouped together (my PubSub is for whatever reason completely broken right now, so I can 100% rule out that this had anything to do with it):

![JMF8UKk](https://user-images.githubusercontent.com/80157503/153308448-11ee80bb-4b15-44aa-b635-1b8baa08f706.png)

![chatterino 2022-02-10 at 00 33 16](https://user-images.githubusercontent.com/80157503/153308386-05793624-f831-496e-a402-b8c2bd22eaff.png)

Also, I managed to reproducibly get this effect on every timeout, until I restarted chatterino, after that everything went back to normal:

![chatterino 2022-02-10 at 00 39 03](https://user-images.githubusercontent.com/80157503/153308950-8998b7f6-18f6-441f-94f9-a1da0f928a62.png)

So my theory on this right now, after seeing that this is in general a problem with replacing messages, is this:

### 1: On receiving a timeout message in the IRC message handler, addOrReplaceTimeout is called on the channel
https://github.com/Chatterino/chatterino2/blob/5490ff50154f3bd1bdbaa67786764c0e3013c57b/src/providers/twitch/IrcMessageHandler.cpp#L439-L442

### 2: addOrReplaceTimeout goes through some logic to find out the right message to replace and calls replaceMessage, also inside of Channel.cpp, either with a replacement PubSub message or an incremented timeout one:
https://github.com/Chatterino/chatterino2/blob/5490ff50154f3bd1bdbaa67786764c0e3013c57b/src/common/Channel.cpp#L141-L147
https://github.com/Chatterino/chatterino2/blob/5490ff50154f3bd1bdbaa67786764c0e3013c57b/src/common/Channel.cpp#L157-L164

### 3: Inside of replaceMessage, the message is replaced in the message_ array of the channel and a signal for the channel widget is invoked with the index of the old message and the new message.
https://github.com/Chatterino/chatterino2/blob/5490ff50154f3bd1bdbaa67786764c0e3013c57b/src/common/Channel.cpp#L223-L231
Interesting about this is that until here everything has worked fine, since when checking in the usercard, CTRL+F, opening a new popup channel, etc. the correct message is replaced, proving that the underlying message array is modified correctly.

The actual error is only related to the visual replacement in ChannelView.cpp:
https://github.com/Chatterino/chatterino2/blob/5490ff50154f3bd1bdbaa67786764c0e3013c57b/src/widgets/helper/ChannelView.cpp#L676-L681

Since that replacement works with an index the only way I can see this issue happening is if the array of the displayed messageLayout objects and the one of the underlying messages are somehow out of sync. I do not believe that this is a race condition, since there were no new messages received in between the first and the second timeout. I have absolutely no Clue how that mismatch between the two arrays could happen though, and its too late at night for me to even try and find out if that is the actual issue and where it happens, but it would explain the issue being reproducible for me today.

**Comment by hemirt** [comment]
Happens also with reconnect messages, this might be the easiest way to replicate, though it does not happen always or consistently, and does also happen in not super active chats. 

( https://github.com/Chatterino/chatterino2/issues/5681 )
