### ISSUE TITLE
Color @usernames stopped working

### ISSUE THREAD

**Issue by KararTY** [Chatterino/chatterino2#2822]
**Describe your issue**
In the recent nightly, **Windows 10, Chatterino Nightly 2.3.2 (commit 3fddafb86, CMAKE)**,
`Color @usernames` setting stopped working.
![image](https://user-images.githubusercontent.com/13697809/119363851-92e8e500-bcae-11eb-9689-c01c89de4bbd.png)

This setting works fine for me on 258851e5729508e7839702ed65ee0d900da00cea.

**Comment by fourtf** [comment]
can't reproduce on 3fddafb

**Comment by fourtf** [comment]
works with nightly built with Qt 12
doesn't work with nightly built with Qt 15

**Comment by Mm2PL** [comment]
wtf is this bug

https://user-images.githubusercontent.com/25011746/122460036-2ad1aa00-cfa1-11eb-8fa6-5b001fba5086.mp4

**Comment by Mm2PL** [comment]
![https://i.imgur.com/7rKR1Az.png](https://i.imgur.com/7rKR1Az.png) this confuses me even more

**Comment by Lubieerror** [comment]
It might be noobish idea, I haven't touched C++ for a while but isn't it move on the lru_cache that doesn't copy max_size (and then because it's 0, the list is cleared)?

I managed to get this bug on all 5 chats. Every time exists check in ChannelChatters failed (inside the _cache_items_map was empty) and then when I moved debugger inside lru_cache::put, the _max_size was 0, where in ChatterSet it shows chatterLimit as 2000.

It's 2am so sorry if I'm (my mind is) trolling Sadge
