### ISSUE TITLE
Highlights redeem points custom sounds

### ISSUE THREAD

**Issue by wHPcz** [Chatterino/chatterino2#2824]
I tried both sound format and sound alert dont work for me. Do u have the same experience?

**Comment by Mm2PL** [comment]
You cannot enable ping sounds at all for *Highlights redeemed with Channel Points* (as indicated by the lack of the *Play sound* checkbox).

**Comment by Felanbird** [comment]
As Mm2PL mentioned above, we opted into disabling the ability to play sounds for `Highlights redeemed with Channel points`, the reason why you are able to set a custom sound for this is because it was just generally easier to set that entire column than it was for each "enabled" highlight.

That being said, I've opened up a discussion for this in https://github.com/Chatterino/chatterino2/discussions/3374 which moves to discuss whether or not we should allow users more freedom for said highlight types.

**Comment by Mm2PL** [comment]
Moved to discussion in #3374.
