### ISSUE TITLE
"Add split" dialog can't be moved with WM hotkeys

### ISSUE THREAD

**Issue by jammehcow** [Chatterino/chatterino2#2835]
**Describe your issue**
When attempting to move the "new split" dialog using WM keybinds (e.g. super + right_arrow) the super key is ignored. This causes the arrow keys (if used for window movement) to act as if they weren't in a key combination. The window also does not move.

The only way I've managed to get around this is to Super + Tab (my bind for switching to recent workspace) which has to be done twice in order for it to register. Seems like the super key is somehow being captured?

**Screenshots**
Example behaviour when moving with Super + {left,right} in bspwm:
https://user-images.githubusercontent.com/4962764/120067828-c4f4af80-c0d1-11eb-838f-6388336a58c9.mp4

**OS and Chatterino Version**
Arch Linux, linux-zen 5.12.7
bspwm + sxhkd, picom
Chatterino 2.3.2 (commit 3fddafb)

**Comment by apa420** [comment]
Question: How do floating windows normally behave for you (popup ones like chatterino one).
Does the window go to the side or does your window manager not allow that and only allows windows which are tiled?
This might have nothing to do with chatterino.

**Comment by apa420** [comment]
Can replicate on dwm.
Using super+, or any other key will result in chatterino just posting , in the textbox.

**Comment by Mm2PL** [comment]
Can replicate on I3.

**Comment by zneix** [comment]
Just tried this one on my setup, I'm pretty sure this is because that dialog takes control over keypresses if you're focused on its elements, as in the line edit for "Channel" or other radio buttons.
@jammehcow, just to perform a healthy sanity check, if you focus the "Add split" dialog and then press on the "Twitch" tab - can you use your WM hotkeys and/or move the split? If so, I'm sure it's safe to assume that the dialog's element might be just taking control over WM keybindings in general while those have focus.

**Comment by Mm2PL** [comment]
This only works in the Twitch tab, therefore there must be some special logic that breaks this and doesn't happen on the IRC tab, probably the Up/Down bindings(?).
