### ISSUE TITLE
Subscribers with Founder badge aren't accurately filtered with author.subbed

### ISSUE THREAD

**Issue by tatemusante** [Chatterino/chatterino2#2860]
Subscribers who also have the founder badge are not filtered correctly with author.subbed. To fix this, I have to create the following filter to filter all subscribers, even those who are founders:
author.subbed || ((author.badges) contains ("Founder"))

![image](https://user-images.githubusercontent.com/40074569/120779512-fc04ff80-c4db-11eb-91e3-c76fae2d7544.png)

Windows 10, Chatterino 2.3.2

**Comment by Felanbird** [comment]
I assume this would just be fixed by including 'founder' in here along with subscriber? 

https://github.com/Chatterino/chatterino2/blob/0a51252b761ac4a846725ce6b6e8cf8bba5efdf4/src/controllers/filters/parser/FilterParser.cpp#L50-L53

**Comment by zneix** [comment]
@tatemusante thanks for a bug report! I managed to fix the issue. Pull Request fixing it has been merged in to master and Chatterino version that has the fix is available in [nightly build](). Feel free to download it, give it a try and in case of any issues/questions feel free to ping me in this issue.

P.S. Sorry that it took so long to get to it, we have a big backlog ;p
