### ISSUE TITLE
Emote refreshing shows animated emotes first but no sub emotes when opening it first time after refresh

### ISSUE THREAD

**Issue by karl-police** [Chatterino/chatterino2#2934]
**Describe your issue**
When refreshing the emotes now, opening the emote tab at the beginning shows all animations, but the rest of the sub emotes are missing. However if you open it again, everything shows.

I think it's because I opened it too fast, but didn't it use to automatically update the emotes in the emote window?

**OS and Chatterino Version**
Windows 10, Chatterino Nightly 2.3.3 (commit a458e32f1)

**Comment by Felanbird** [comment]
Can replicate but it's not an issue, you are just opening the menu before the reload has finished.

**Comment by zneix** [comment]
As felanbird mentioned this is not a bug - you're trying to open emote menu before the emoteset data finishes loading.

> didn't it use to automatically update the emotes in the emote window?

It still does that, thing is loading emoteset data takes a bit longer now due to limitations regarding emote data imposed by Twitch. There's no real workaround for this and everything works - you just gotta wait a little longer, depending on how many emotesets (subs) you have.

**Comment by jammehcow** [comment]
@zneix you might want to reopen this issue. I saw this happen yesterday at least twice yesterday after having chatterino open for a long time.

There were after an open and not a refresh so maybe this is a different issue.

**Comment by zneix** [comment]
> There were after an open and not a refresh so maybe this is a different issue.

As karl described:

> However if you open it again, everything shows.

his emotes appeared there after a little bit, so I assume it's simply what I addressed in my comment - you just have to wait.

What you describe sounds like either emoteset data requests failing or not working the first time we initialize `TwitchAccount::emotes_` upon calling `TwitchAccount::loadEmotes`. I'll definitely have a look into this and open a new issue if there's an actual issue with emoteset data not being set correctly due to some weird logic with the hacky workarounds inside `TwitchAccount::loadEmoteSetData`.

**Comment by jammehcow** [comment]
Could be related to the mass timeout issue we're having with our timeout timer? Once I get through that I'll see if it's resolved.
