### ISSUE TITLE
Color picker HTML field weirdness

### ISSUE THREAD

**Issue by dojima** [Chatterino/chatterino2#2939]
**Describe your issue**

Typing in the HTML field in the color picker window doesn't work as expected.  The third character typed duplicates all characters, e.g., typing '123' results in '112233'.  Possibly intended?  But strange.

**OS and Chatterino Version**

Windows10, Chatterino 2.3.2.

**Comment by leon-richardt** [comment]
That was not intended by me (who is responsible for the original feature). The behavior is caused by the input validation set up for the text field:
https://github.com/Chatterino/chatterino2/blob/6355742b6ed01ff54b66752655e4c5c4290c0231/src/widgets/dialogs/ColorPickerDialog.cpp#L355-L363

Worth a fix imo

**Comment by Mm2PL** [comment]
I see that `#RGB` is meant to be interpreted as `#RRGGBB`. However I believe overriding what the user writes is a bug.

Src: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#syntax_2
