### ISSUE TITLE
Variable placeholders for custom commands

### ISSUE THREAD

**Issue by MrAuro** [Chatterino/chatterino2#2943]
**Describe your issue**
Add a `{channel}` placeholder for commands that would put the current channel. This would be useful for opening moderation popout widgets, like reward queue, predictions, etc.

**Screenshots**
![example](https://user-images.githubusercontent.com/35087590/124041784-8f472d00-d9d5-11eb-8a78-ec33009c3e51.png)

**OS and Chatterino Version**
Windows 10 - Latest Nightly

**Comment by zneix** [comment]
I feel like general idea of placeholders in the custom commands for some other properties would make sense. This would need some good refactor of how we handle custom commands though.
Some ideas:
1. `{channelid}` - same as channel, but in form of ID instead of login
1. `{usernmae}` - substitution for username of currently logged in user (useful on multi-account setups).
1. `{userid}` - userid of currently logged in user
1. `{title}` - current stream title
1. `{game}` - current stream game

**Comment by Mm2PL** [comment]
I've been thinking about using filters parser for this, it would need a way to return a qvariant/qstring but other than that it seems feasible. 🤔

**Comment by ALazyMeme** [comment]
I have also been thinking about an `{if}` variable, which could also be used in a moderation sense:

`{if:"{1}","{1}","{channel}"}`

If there is a parameter specified, then choose that, else go with the channel.

Could also go with a default parameter, `{channel;1}`: default channel, if first argument available then use that
