### ISSUE TITLE
can't click "copy" on the commit hash in the about tab

### ISSUE THREAD

**Issue by mlnrDev** [Chatterino/chatterino2#2955]
**Describe your issue**

I can't click "Copy" for the commit hash in the about tab. The copy option also looks weird, kinda blurry.

**Screenshots**

![](https://i.imgur.com/TJn8o4r.gif)

**OS and Chatterino Version**

Windows 10, Chatterino [3b0d62f5c](https://github.com/Chatterino/chatterino2/commit/3b0d62f5c)

**Comment by caneleex** [comment]
additionally, the date of build missing after the comma.

**Comment by pajlada** [comment]
This is because you can select the text. If you select the text you'll see the option is available
![image](https://github.com/Chatterino/chatterino2/assets/962989/79c14f14-54e5-4137-a26d-1d7915bfe25f)
![image](https://github.com/Chatterino/chatterino2/assets/962989/32a0120e-b014-4066-81a8-f7258bf245a1)


If you only want to copy the link, you can copy the link location

![image](https://github.com/Chatterino/chatterino2/assets/962989/a482a5fe-adfb-415e-bc53-846d4cbdc475)


Generally, if you're asked to share what c2 version you're running, you'd be asked to copy all of the text
