### ISSUE TITLE
chatterino is laggy for multiple things

### ISSUE THREAD

**Issue by caneleex** [Chatterino/chatterino2#2956]
**Describe your issue**

Chatterino now feels really laggy for things like loading the emotes popup, seems like the fetching is blocking, especially for emojis. Opening the user popup also feels more like laggy than before. Closing popups also feels laggy.

**Screenshots**

![](https://i.imgur.com/RmQQcmA.gif)

**OS and Chatterino Version**

Windows 10, Chatterino [3b0d62f](https://github.com/Chatterino/chatterino2/commit/3b0d62f5c)

**Comment by zneix** [comment]
Do you describe as laggy for `multiple things` in scope of just emote picker? If so, your title could use a little better wording.
Also, does this only occur when you open the emote popup for the firs time since the application startup? Keep in mind that there're lots of emojis and loading all of those takes quite a while. I think it shouldn't be as laggy when you open it again.

**Comment by caneleex** [comment]
clicking the user popup also freezes the app for a bit, so I think "multiple things" is fine. no, the emote menu lag occurs every time I open it, not just after the startup.

**Comment by leon-richardt** [comment]
Might not be related at all but we messed with caching in https://github.com/Chatterino/chatterino2/pull/2947.

**Comment by caneleex** [comment]
well, now it's fine again, and I didn't even change anything. might have just been windows having a stroke (like always)
