### ISSUE TITLE
Sub Emotes not longer in "Subs"-Section of Emote menu

### ISSUE THREAD

**Issue by AutofireDev** [Chatterino/chatterino2#3001]
**Describe your issue**

**OS and Chatterino Version**

**Comment by sando** [comment]
Thanks for the very descriptive bug report 🙂👍

In all seriousness, could you please describe further the issue you are having with sub emotes? It sounds like it could be related to an existing issue.

**Comment by Mm2PL** [comment]
This bug report doesn't provide information specific enough to reproduce or fix it.

**Comment by Felanbird** [comment]
While this report is on the poor side, I have had this issue a few times, the emotes go into the "twitch" section instead of their correct section. 
Just seems to be the channel information failing to load, f5 did not fix it but I figured that d6b5921 would probably better handle that fact, so I never bothered reporting it, as I have not updated to that point to test it, and replication isn't exactly easy.

Steps to Reproduce:
1. Get a new gifted sub
2. Press F5
3. Hope that the new emotes go into wrong section
4. 🍶 

IIRC restarting did fix it and placed the emotes back into their correct section, which is my reasoning for thinking the information required just failed to load, and wasn't re-obtained on f5.

**Comment by zneix** [comment]
I am almost sure you mean emotes going into wrong tab is occuring on chatterino builds running older commit than 002129009df0743e1edb9b1e8c659f3b621a9e60 (#2905)

> Hope that the new emotes go into wrong section

@Felanbird This has nothing to do with emotes going into wrong tab, it doesn't matter if you just got gifted and that's a new emoteset you've got or not. I myself got gifted a forsen sub couple days ago and can confirm that emotes do refresh even without pressing F5 (see https://github.com/Chatterino/chatterino2/issues/1285#issuecomment-869015061). All you have to do is receive a `USERSTATE` message, which you can get by either joining any channel or typing any message in any chat.

Information is indeed fetched properly on F5 - you just have to wait a little, it can take longer time now so if you've pressed F5 and emotes did appear in wrong section you should've closed emote popup and opened it again after like 5-10 seconds and I'm 100% sure emotes would appear in correct sections if you're past 002129009df0743e1edb9b1e8c659f3b621a9e60 (#2905).
