### ISSUE TITLE
new highlight window in addition to /mentions

### ISSUE THREAD

**Issue by Z1c3rzzzi60** [Chatterino/chatterino2#3022]
A highlights tab that you can put the highlights, so that not everything appears in the /mentions tab and thus have everything more organized.

**Comment by jammehcow** [comment]
There's an issue template you should use instead of creating a blank issue - it's there for a reason.

The purpose of the `/mentions` tab is to show your highlights. Splitting off into a `/mentions` and `/highlights`  sounds like a waste of a tab. You can until the "show in mentions" checkbox next to a highlight to disable it from showing in the `/mentions` tab.

**Comment by sando** [comment]
The other way (i.e. still collect highlights but have a dedicated tab for just mentions) is already possible in Chatterino too. Add another `/mentions` split, then create a [filter](https://wiki.chatterino.com/Filters/) for your username and apply it to the `/mentions` split where you only want to see when you're mentioned.

**Comment by apa420** [comment]
As described by @sando this is already possible by the use of filters.
