### ISSUE TITLE
Copying username in usercard copies login-name while displays display-name

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#3070]
**Describe your issue**

Clicking the copy username button copies the login-name while the label next to it shows the display-name.

**Screenshots**

![if you see this i von zulul](https://user-images.githubusercontent.com/25011746/126893718-701e16fb-98b2-46f5-a28b-dfd249199f87.png)

**How to reproduce**

  1. `/usercard testaccount_420` or open a user popup any other way,
  2. Click copy username button,
  3. Paste it somewhere, see that it pasted `testaccount_420` instead of `테스트계정420` which was displayed on the label.

**OS and Chatterino Version**

Chatterino + Dankerino patches 2.3.3 (commit bdf45c408ac53c5ff843f1949f54d2687fa4641a, upstream ae9f92de)
also works on Chatterino 2.2.3-beta2 (commit 821b0e3d5)

**Comment by talneoran** [comment]
I could see a reasoning to show both the display name and the login name in the usercard in cases where they are different like this, but I think the copy behavior should still be the login name. At least from my experience when I copy a username it is usually to paste it into something that requires the login name as input, such as the usercard command itself or some other locations in the app.

**Comment by zneix** [comment]
This is the one thing I forgot about when adding the display name to the usercard in #2160. This should just make use of the `Settings > Advanced > Username style` setting I suppose - you should be able to copy exactly what you see.

**Comment by pajlada** [comment]
Quick fix:
Respect username style in display
Respect username style in copy

Long fix:
Quick fixes
If the user has a localized username, include a second copy button with a tooltip "copy login name". Buttons should probably look different, not sure in what way though

**Comment by sando** [comment]
Setting the copy button to the localised name feels like a step backwards. I'd like to be able to see the localised name, but I almost never need to refer to it. I can only think of a couple rare use cases where copying the localised name would be helpful, otherwise it'll be more of a hinderance whenever I want to use it.

Aside from what's already been suggested, the other two options I can think of are:
* Regardless of username style setting, display both username and localised name on separate lines, and have a copy button for each
* Enable the text cursor/make the name label highlightable, display both username and localised name, users can highlight and copy what they want manually
