### ISSUE TITLE
Can't see the messages I send in a SLOW OFFLINER chat.

### ISSUE THREAD

**Issue by karinaalolz** [Chatterino/chatterino2#3075]
I am an offliner in a CCs chat and my messages are not sending/not showing up. I've tried everything. What can i do?

**Comment by sando** [comment]
Please detail what "everything" is. See https://wiki.chatterino.com/Help/#why-are-my-messages-being-sent-in-webchat-but-not-in-chatterino and let us know of the results.

**Comment by karinaalolz** [comment]
> Please detail what "I've tried everything" is. See https://wiki.chatterino.com/Help/#why-are-my-messages-being-sent-in-webchat-but-not-in-chatterino and let us know of the results.

What I mean by that is that I read articles on how to resolve this issue but it didn't work for me. And first of all, thank you for the link, I've read through it. The chat is still empty, about 4 people are there.

**Comment by Felanbird** [comment]
Although you have closed this issue as I assume the issue has been resolved, if you are still on 2.3.2 feel free to update to the most recent nightly found here: https://github.com/Chatterino/chatterino2/releases/tag/nightly-build
As the most common variation of this issue was fixed in 8639f450f23d4b58a07623dd568a4cd7c1bf4e03
