### ISSUE TITLE
Some old event emotes don't show up in Chatterino anymore

### ISSUE THREAD

**Issue by Trung0246** [Chatterino/chatterino2#3154]
As title said, old twitch event emotes did not show up anymore in 2.3.4. Previously those emotes did show in 2.3.3 stable (probably recent switch from v1 to v2 api is the problem? Not sure...)

I purged my cache (by deleting the Cache folder) and the issue still presist.

![image](https://user-images.githubusercontent.com/11626920/128656857-481174db-b62e-4546-8a37-785d86168da9.png)
![image](https://user-images.githubusercontent.com/11626920/128656921-c3a35de5-81cb-4a42-8eba-d76debb8e07b.png)

Version: 2.3.4 stable
OS: Windows 10

**Comment by Felanbird** [comment]
@Trung0246 they are in the "Global" tab xd

**Comment by Felanbird** [comment]
**Note for devs:** This was an undocumented and unintentional change via cd7758a28ef430ff92c957d3dee9b13f65b5ef43, but might be for the best? 

Logically these emotes are seen as Global emotes, and as I've learned today, the ancient "Twitch Pokemon" emotes exist in this tab as well. 
While we probably wouldn't take steps to move this under normal circumstances, since Kraken will be deprecated in 6 months, an accidental change to move this to a more "logical" position in the emote menu might not be terrible? idk

As seen by the screenshots, the emotes that still exist under `qa_TW_Partner` are special cases and are resolved by `ivr` requests.


**Logic from somebody who actually knows what they are talking about:**
![image](https://user-images.githubusercontent.com/41973452/128674080-75242a2a-4401-4283-a27b-57186c01ee55.png)
![image](https://user-images.githubusercontent.com/41973452/128674095-9b6d6c54-e440-4c2a-8b0a-0fdb550139dc.png)

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/128680599-fa004844-6ec5-42db-b44b-d45cfab67da4.png)
![image](https://user-images.githubusercontent.com/41973452/128680682-0e213164-6628-4254-b257-c4e9150a9e83.png)


![image](https://user-images.githubusercontent.com/41973452/128679591-ab5b159d-9cd1-4f50-b043-92f3e64d1515.png)
Basically we are probably just going to leave these emotes in the `Global` tab, since as far as we are currently aware, when Kraken is deprecated we will have no Helix alternative to replace the emotes in the menu. - Although this may change in the future.

**Comment by Trung0246** [comment]
> @Trung0246 they are in the "Global" tab xd

I rarely check Global tab OMEGALUL

**Comment by Felanbird** [comment]
> Anyways seems like we have to move the rest to Global tab?

I'll make a note in #2961.

**Comment by Trung0246** [comment]
Quick question ( just opened my laptop for this Pepega ): you said that now those emotes appear in Global tab for you but for me it doesn't show anything or did I miss something?
![image](https://user-images.githubusercontent.com/11626920/128763049-120a3cd9-9509-4855-9d62-3adb1d5b6419.png)

**Comment by Felanbird** [comment]
> Quick question ( just opened my laptop for this Pepega ): you said that now those emotes appear in Global tab for you but for me it doesn't show anything or did I miss something?
![image](https://user-images.githubusercontent.com/41973452/128763252-4e9a32f8-deb0-404f-91ce-a02d89e80a3d.png)

**Comment by Trung0246** [comment]
Ok now that's weirder wtf

**Comment by Felanbird** [comment]
> Ok now that's weirder wtf
> 
> Wait nightly Chatterino?

I'm currently on a build that's equivalent to cd7758a

Go to ⚙️ -> About and check your commit in ( brackets )

**Comment by Trung0246** [comment]
https://github.com/Chatterino/chatterino2/commit/4e5170799

![image](https://user-images.githubusercontent.com/11626920/128763754-61412594-423b-4a3c-9f19-709d691b3582.png)

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/128765859-2b01d4d3-3aee-4b37-addd-0f9932d90c03.png)
From manually checking out 4e51707

**Comment by Nerixyz** [comment]
This should be fixed by #5239.

**Comment by pajlada** [comment]
Fixed by #5239
