### ISSUE TITLE
Allow /usercard to use a different channel context

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/chatterino2#3167]
**Describe your issue**
Sometimes, I would like to see a user card in a different channel context. Instead of having to open that channel in a new split, I would prefer to be able to type the chat command `/usercard <user> [channel]` to view `user`s user card in the context of `channel`. If the `channel` argument is omitted, the current behavior (opening the user card in the current channel's context) is used.

Also, the name of the channel the user card belongs to should be mentioned somewhere. This could just be the window title or a separate field on the user card itself.

**Comment by pajlada** [comment]
This is a good issue for new contributors.

The code for `/usercard` is [here](https://github.com/Chatterino/chatterino2/blob/master/src/controllers/commands/CommandController.cpp#L476-L492).

It would need to handle the `words[2]` parameter as a `channelName`, call `stripChannelName` on it (see above command for how that's done), and get a channel using the `getApp()->twitch2->getChannelOrEmpty(channelName)` function.

Further questions:
What happens if the user does not have the channel open in any split?
