### ISSUE TITLE
Chatterino defaults to the last known game on existing splits if there is no game set

### ISSUE THREAD

**Issue by ALazyMeme** [Chatterino/chatterino2#3224]
**Describe your issue**
When there is no game set, Chatterino appears to show the last known game as the game.

**Screenshots**
Chatterino:
![image](https://user-images.githubusercontent.com/12804673/132116453-a4cc39fe-f441-4f67-acf6-6dfda94c0373.png)

Twitch website:
![image](https://user-images.githubusercontent.com/12804673/132116460-a3474abc-1a2f-4e59-a5d9-ad2a1322c6e0.png)

**OS and Chatterino Version**
Windows 10, Chatterino Nightly 2.3.4 (commit c156094d7, )

**Comment by Felanbird** [comment]
IIRC this is specific to when the game is changed from `[game] -> [nothing]`, as when opening a tab of a user under no category, nothing appears as intended.
![image](https://user-images.githubusercontent.com/41973452/132119165-0d61e68a-77e6-4bf0-8d40-a5f40a333605.png)

**Comment by jammehcow** [comment]
Did some digging, this is caused by [TwitchChannel.cpp](https://github.com/Chatterino/chatterino2/blob/414313726e4a0c05489f3e1bcc66c8d5e4bf64ab/src/providers/twitch/TwitchChannel.cpp#L744) calling the Helix API with an empty game ID as "nothing" has no game ID. A simple workaround would be to check for an empty string before this method and update the stream title accordingly without making an API call.

Will look at patching.
