### ISSUE TITLE
Pressing enter inputs a literal newline into split input box

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#3363]
**Describe your issue**
When you press enter, a new line gets put into split input box

**Screenshots**
https://user-images.githubusercontent.com/3091645/143096539-f771154f-98e2-41e6-9418-6c42e115526c.mp4 (ear warning)

**OS and Chatterino Version**
Chatterino nightly + dankerino 2.3.4 commit 608965eba,

**Comment by Felanbird** [comment]
Partial Duplicate of #3361 - flashing variation fixed by #3362

Also a duplicate of #2844 - after the above PR is merged, this will only happen when chatterino is not fully focused.

**Comment by Mm2PL** [comment]
I can't see how this is a dupe of #3361. This behavior stems from transitioning to QShortcuts from event filters. The old event filter system used to blanket capture every single Return key press, while the new one requires modifiers to not pass the event to the input box (ie insert a literal new line).

**Comment by mWalrus** [comment]
im still experiencing this issue on the latest commit

**Comment by Felanbird** [comment]
> I can't see how this is a dupe of #3361. 

I believed it to be a partial dupe because #3362 fixed it. In the video with Chatterino focused and enter held down, a newline is constantly spawned and deleted, with the code from said PR, this is no longer possible.

That being said, when Chatterino is not fully focused, the newline does continue to be generated as if shift was being held down, but that was not the issue shown by the video.

**Comment by mWalrus** [comment]
For me the issue is not exactly as shown in the video but whenever i type out a message and try to send it by pressing enter, chatterino will input a literal newline in the input box instead of sending the message on every attempt. I am unable to send any messages because of this.

I am on Arch Linux running the chatterino2-git package from the AUR which is on the latest commit of chatterino and im using a tiling window manager which means i have to actively focus the window to be able to interact with it and i have had no other issues with focus on any other application i use. (I'm not sure if this is what you mean by focus but maybe its relevant information anyways)

**Comment by TETYYS** [comment]
> For me the issue is not exactly as shown in the video but whenever i type out a message and try to send it by pressing enter, chatterino will input a literal newline in the input box instead of sending the message on every attempt. I am unable to send any messages because of this.

wtf i just started having this issue today after a pc restart, i can't send anything anywhere

**Comment by TETYYS** [comment]
Latest master doesn't have the issue described in first post anymore.

**Comment by mWalrus** [comment]
I just realized I can work around my issue by manually adding a hotkey for sending messages and binding it to the enter key. Still feels unintended.

**Comment by Mm2PL** [comment]
> oh, turns out ALL of my hotkeys were deleted for some reason

this worries me

**Comment by mWalrus** [comment]
> maybe something with windows support?

My hotkey list was empty aswell on linux

**Comment by ALazyMeme** [comment]
I do indeed have this issue on commit a4ae09f04. Sometimes it seems to "bug out" and continually go to a new line instead of sending the message. Often resulting in me having to send a random message in another chat, then I can hit enter on the message I wanted to send.

**Comment by bjwest** [comment]
Issue still persistent on commit d21bdc695 or commit 0412658b1 for Chatterino7, both latest as of Noon, CST.  Last working Chatterino7 for me was commit 8786c24f5, can't say which previous Chatterino2 worked properly.

Neon Linux, QT 5.15.3

**Comment by Felanbird** [comment]
> can't say which previous Chatterino2 worked properly.

It was [this version](https://github.com/Chatterino/chatterino2/releases/tag/pre-custom-hotkeys-real) - we made this backup release in the case #2340 caused an issue like this. That being said this is still a focusing issue, and you should be able to visually see if the channel header at the top is highlighted in white or blue. If it's white click into Chatterino (turn the channel name blue) and enter will work as intended again.

**Comment by bjwest** [comment]
Channel name blue or white makes no difference for me.  Binding the return key to send the message is a working workaround for now.
