### ISSUE TITLE
Confirmation to close the split or restoring a closed split

### ISSUE THREAD

**Issue by Chancuu** [Chatterino/chatterino2#339]
A set shortcut to close splits is CTRL + W and I often find myself pressing that somehow and then my current tab closes.

I suggest to add a " Are you sure you want to close this split?"  whenever you press CTRL + W

Not sure if you would have to add that confirmation   in the option from the screenshot

![xhuemlz](https://user-images.githubusercontent.com/37437992/38631928-7731e0fc-3dbb-11e8-9e5a-7a8755edebfb.png)

**Comment by fourtf** [comment]
Maybe a shortcut to restore the split right after closing it would be a better solution.

**Comment by pajlada** [comment]
Further discussion was held in #1535 which might be relevant

**Comment by Felanbird** [comment]
Also discussion held in #2072

**Comment by Felanbird** [comment]
This issue is technically resolved via the following 2 options:
 - As mentioned by fourtf, the better solution of re-opening `CTRL+G` has been around since #795
 - The ability to disable the `CTRL+W` keybind was added recently in #2340.

If we think the confirmation approach is better we can keep this issue open, otherwise there are tools to work around it.
