### ISSUE TITLE
Right Click Context Menu Shows On Other Screen 

### ISSUE THREAD

**Issue by Nerxxy** [Chatterino/chatterino2#3497]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Upon right clicking anywhere on chatterino the context menu appears on my main monitor instead of the monitor chatterino is placed

### Screenshots

![image](https://user-images.githubusercontent.com/37718547/149314435-27c7ab7a-2225-4d42-8839-b420aaadc56a.png)

![image](https://user-images.githubusercontent.com/37718547/149314612-b32d0414-709c-419d-b586-207f606be565.png)

### OS and Chatterino Version

Chatterino 2.3.4 (commit 4e5170799) Windows 10 21H2

**Comment by zneix** [comment]
This might be a weird question, but have you perhaps changed monitor resolutions / (dis)connected monitor(s) since chatterino has started? I think this could have to do with Chatterino only acknowledging monitor dimensions at startup and then getting lost, displaying popups / tooltips in wrong places - I've noticed this weird behavior after: I start chatterino while only 1 monitor is connected, connect 2nd monitor, spawn a popup like the one you've shown.

**Comment by Nerxxy** [comment]
Not that i can remember, but this question im guessing if i reload chatterino it "should" fix it? I'll give it a try and report back

**Comment by Nerxxy** [comment]
Ok, you were right in asking that, i just restarted chatterino and it fixed the issue
