### ISSUE TITLE
Viewer List window opens in the top left of the screen

### ISSUE THREAD

**Issue by DatL4g** [Chatterino/chatterino2#3515]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When I open the Viewer List window it opens in the top left corner of my monitor.
But it's not even opening at 0x0, it's opening above the first pixel so I cannot close the window.

![viewer_list](https://user-images.githubusercontent.com/46448715/149639293-305495f9-9c62-4bf1-ad6a-03bfed6eaf5a.png)
This screenshot is taken from the very top left corner.
I have to double-click on the window so it moves in the Chatterino window and then I can close it.

Maybe it's better to display it in a window like the UserCard or the Chatterino Window so we have a top bar like this:
![image](https://user-images.githubusercontent.com/46448715/149639361-03bac526-831f-4338-b92e-52a4667bd9d9.png)

### OS and Chatterino Version

Chatterino 2.3.4 (from RPM) on Fedora 35

**Comment by Mm2PL** [comment]
Looks related to #2583 to me.

**Comment by DATL4G** [comment]
I don't think it's related to #2583 

It has nothing to do with resizing or remmebering the size

**Comment by bathtubdev** [comment]
@DATL4G 

Could you please provide this information:

- Name of Desktop Environment
- Name of UI Theme used with the Desktop Environment
- Name of Window Manager


Thank you

**Comment by DATL4G** [comment]
@bathtubdev sure here it is:

- Name of Desktop Environment: **Gnome (Shell 41.3)**
- Name of UI Theme: **[Orchis-pink-dark](https://github.com/vinceliuice/Orchis-theme)**
- Name of window System: **x11**
- Name of Window Manager: (not sure how to check that, but it's the Fedora 35 default so) **Gnome Shell on mutter** (I think)

**Comment by bathtubdev** [comment]
I'm starting to mirror your setup on my computer. I'll let you know when I've done a complete test.

**Comment by DATL4G** [comment]
Alright just to mention it (idk if it's somehow related to this), I have a 2560x1440 monitor (as primary) and a 1920x1080 monitor on which Chatterino is opened and this issue occurs.

And even if I open Chatterino on my primary monitor, the viewer list opens on the second one

**Comment by bathtubdev** [comment]
You're 100% sure that the 2560x1440 monitor is selected as the primary monitor in Settings?

**Comment by DATL4G** [comment]
100% sure yes

![image](https://user-images.githubusercontent.com/46448715/149641006-278253e1-8ddb-49f7-aa2c-7d40feb1b05c.png)

(for non german speakers: Primärer Bildschirm means Primary monitor)

**Comment by bathtubdev** [comment]
@DATL4G 

Ok. From my testing: this is most likely some kind of issue with X11 on FEdora Gnome. I couldn't get mutter to run, so there's a chance it could be that as well, since it's Wayland + X11, essentially. 

When I login with regular Gnome (Wayland), I have 0 issues with the viewer list on my 2 3440x1440 21:9 monitors. But when I login with X11 Gnome, the viewer list doesn't have a menu bar that I can grab onto with my cursor and adjust/move; it just has an X button and a button under it that brings the viewerlist into Chatterino. 

Try this:

- Open the viewer list.
- Double left click on the vertical black line that has the words "Viewer List" in the bottom left corner of that window.
- This should bring the viewer list into the Chatterino window.

You could use this a temporary solution. I haven't tried this on other distributions yet, but from my experience with this (recent versions of Fedora Gnome using any form of X11 with Chatterino):

When opening the viewer list, that window is permanently stuck. There is no menu bar like any other windows in any other programs. You can double left click on the vertical black line on the left side of the viewer list window to bring the window into the Chatterino window.

**Comment by DATL4G** [comment]
@bathtubdev

Okay I discovered the workaround myself already (that's what I meant in the issue below the screenshot)
> I have to double-click on the window so it moves in the Chatterino window and then I can close it.

As far as I can say this behaves the same on PopOS 20.04 and (default configuration) but I cannot give further information for this because I don't have this distro installed anymore but yeah just to mention it's not only on Fedora

**Comment by bathtubdev** [comment]
> Author

Ok thanks for the information. I'll look into that as well.

**Comment by bathtubdev** [comment]
Ok thanks for the information. I'll look into that as well.

**Comment by pajlada** [comment]
I believe this is fixed in the latest nightly. Feel free to re-open this if I'm mistaken
