### ISSUE TITLE
Right clicking usernames to mention can sometimes start selecting text

### ISSUE THREAD

**Issue by brian6932** [Chatterino/chatterino2#3605]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Once the bug triggers, you will be stuck selecting, until you left click twice

### Screenshots

https://i.nuuls.com/oHJYQ.png
https://i.nuuls.com/wJBq0.png

### OS and Chatterino Version

Chatterino Nightly 2.3.4 (commit 980a3e1b, built on 2022-03-07) on Windows 10

**Comment by LosFarmosCTL** [comment]
Can reproduce, macOS Big Sur 11.6 (20G165)

**Comment by killertofus** [comment]
can't reproduce Plasma 5.24.3 arch Wayland

**Comment by jammehcow** [comment]
Can reproduce, Arch Linux BSPWM on Chatterino 2.3.4 (commit [1e3fc45d](https://github.com/Chatterino/chatterino2/commit/1e3fc45d))

The issue appears to be that the double click handler ([ChannelView.cpp:2083](https://github.com/Chatterino/chatterino2/blob/master/src/widgets/helper/ChannelView.cpp#L2083)) isn't checking what mouse button was clicked and disabling of the double click state is only triggered when the left mouse button is released ([ChannelView.cpp:2083](https://github.com/Chatterino/chatterino2/blob/master/src/widgets/helper/ChannelView.cpp#L1637)). That's why double clicking the left mouse button stops the right click's selection - it retriggers the expected double click behaviour.

I'll add a left button check to the double click event.
