### ISSUE TITLE
All commands deleted 

### ISSUE THREAD

**Issue by iamlodd** [Chatterino/chatterino2#3841]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Anyone else have chatterino remove all of their commands? Loaded up chatterino today and none of my sub hype commands were there anymore just all removed... any reason this happens? Did I have too many commands made?

### Screenshots

N/A 

### OS and Chatterino Version

Chatterino 2.3.5

**Comment by Felanbird** [comment]
It happens when you incorrectly turn your PC off - during the panic of windows telling Chatterino SHUT DOWN IMMEDIATELY, the file gets corrupted (lost for metaphors sake) and on next startup you have no commands.

Close Chatterino and do the following:

Press win+R | enter `%appdata%\chatterino2\settings` | OK
You should see a bunch of commands.json-bkp-# files, select the oldest one (#9) and open it in a text editor.
If your commands are properly in that file, (with chatterino closed) rename said file to just `commands.json`
Then start Chatterino back up

**Comment by iamlodd** [comment]
> It happens when you incorrectly turn your PC off - during the panic of windows telling Chatterino SHUT DOWN IMMEDIATELY, the file gets corrupted (lost for metaphors sake) and on next startup you have no commands.
> 
> Close Chatterino and do the following:
> 
> Press win+R | enter `%appdata%\chatterino2\settings` | OK You should see a bunch of commands.json-bkp-# files, select the oldest one (#󠀀9) and open it in a text editor. If your commands are properly in that file, (with chatterino closed) rename said file to just `commands.json` Then start Chatterino back up

You are amazing thank you! Fixed

**Comment by Felanbird** [comment]
In case you run into the same issue in the future, you can copy paste the entire `settings` folder somewhere else on your PC, so if you restart and don't notice your commands are gone until long after your backups are re-generated, you'll at least have backups from that specific date.

`%appdata%\chatterino2` or just hop back 1 folder
