### ISSUE TITLE
Multi-channel search doesn't support searching with predicate.

### ISSUE THREAD

**Issue by Foretack** [Chatterino/chatterino2#3870]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When using predicate such as `user:forsen` or `is:ban` in the multi-channel search nothing shows up. 

If the word `user:forsen` is written in a chat I do get a result of the message mentioning it, but this doesn't happen with `is;ban` for some reason.

### Screenshots

![image](https://user-images.githubusercontent.com/69414142/180016823-ab8506eb-c4f0-4fc6-b6b4-8fa5a1de3284.png)

![image](https://user-images.githubusercontent.com/69414142/180017909-568a5f6e-07ce-47b2-a1c1-f9b78e35a20f.png)

![image](https://user-images.githubusercontent.com/69414142/180018056-1b3b5085-9e33-4e31-9c21-e64464f3818c.png)

### OS and Chatterino Version

Chatterino Nightly 2.3.5 (commit 9aa15f1f modified) built on 2022-07-16 with Qt 5.15.2, Windows SDK, MSVC 193231332 Running on Windows 10 Version 2009, kernel: 10.0.19044

**Comment by jammehcow** [comment]
Happy to look into this either today or this weekend

**Comment by jammehcow** [comment]
Issue is caused by the deduplication pass done to filter out messages from the same channel across multiple splits ([SearchPopup.cpp:191](https://github.com/Chatterino/chatterino2/blob/9aa15f1ff59d3cbb317aa5287030736356e0a77d/src/widgets/helper/SearchPopup.cpp#L191)). System messages don't have a message ID, causing all system messages to appear "duplicate" when this check is done.

I'll PR a fix in today.
