### ISSUE TITLE
Migrate /emoteonly command to Helix API

### ISSUE THREAD

**Issue by jammehcow** [Chatterino/chatterino2#3966]
As part of Twitch's announced deprecation of IRC-based commands ([see here for more info](https://discuss.dev.twitch.tv/t/deprecation-of-chat-commands-through-irc/40486), the `/emoteonly` command needs to be migrated to use the relevant Helix API endpoint.

Helix API reference: https://dev.twitch.tv/docs/api/reference#update-chat-settings

Split from #3956

**Comment by Nerixyz** [comment]
I'd like to migrate this command.

Since this command and others use the same Helix API call I'd like to migrate them as well. I'm thinking of making two PRs: one that implements the Helix call and one or two commands (`/emoteonly{,off}`), and the other one that implements the rest of the commands.

List of commands:

- #3966 (this one)
- #3967 
- #3968 
- #3969
- #3975 
- #3976 
- #3977
- #3978
- #3981 
- #3982
