### ISSUE TITLE
Dock Icon revert back to default.

### ISSUE THREAD

**Issue by reiryokusama** [Chatterino/chatterino2#3991]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I try to change Chatterino dock icon on my MacOS Monterey 12.6.
When i open the application - it's revert the icon to default one.
When i close the app - it's put back my custom icon.
How to fix this? I tried to use also IconChamp and cDock.
Tried to change icns in Resource folder of application.

### Screenshots

![SCR-20220916-9sx](https://user-images.githubusercontent.com/113656412/190554250-a2b9dfb1-a1e6-4e8d-bec6-abc4105cdc0f.png)
![SCR-20220916-9tg](https://user-images.githubusercontent.com/113656412/190554293-a823cfa0-dd76-43e7-9e28-52ec1c6c205e.png)

### OS and Chatterino Version

Chatterino 2.3.5 (commit c6ebb70e modified) built with Qt 5.15.2 Running on macOS 12.6, kernel: 21.6.0

**Comment by kageyama-h** [comment]
This issue is also present on MacOS 13.0.1 Ventura, under M1 Pro.

**Comment by kageyama-h** [comment]
This issue may be circumvented by implementing #2204

**Comment by LosFarmosCTL** [comment]
> This issue may be circumvented by implementing #2204

While there would be less incentive to change the icon after that is done, the core issue still remains. I remember looking into this since I have encountered it myself, but I got sidetracked by trying to fix the macOS icon situation as a whole and just forgot about the entire thing. I always wanted to fix both issues but I can't promise anything will happen soon, very busy with university right now, plus I am on vacation for 2 more weeks and don't have a computer with me.

Fwiw, the icon switching was caused by #3554, so an IFDEF around the setWindowIcon call to exclude macOS would fix this issue, setting the icon is kinda unnecessary anyways considering that it's already supposed to be included in the application bundle. Would have to be IFDEF'd out for macOS anyways as soon as the bundle gets a separate icon in the new style.

**Comment by kageyama-h** [comment]
I understand your predicament. In that case, perhaps it would be best to meet a compromise and just change the icon for the MacOS binary, and leave #3554 open.

**Comment by LosFarmosCTL** [comment]
> I understand your predicament. In that case, perhaps it would be best to meet a compromise and just change the icon for the MacOS binary, and leave #3554 open.

Should not be an issue to just exclude that particular code line for macOS, as I said it's kinda unnecessary anyways.

The icon changing was the part I failed at, generating the correct iconset file turned out to be a bit weird and I just forgot about it after I didn't manage to do it immediately 😁

The qt support article detailing how to set the actual icon in the end, after generating the iconset using `iconutil` if anyone wants to pick this up: https://doc.qt.io/qt-6/appicon.html
