### ISSUE TITLE
Add option to hide leading user mention in replies

### ISSUE THREAD

**Issue by Nerixyz** [Chatterino/chatterino2#4044]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

As you can see in the screenshot below, replies in twitch chat have a leading mention. The mentioned user is displayed twice on screen (in the "Replying to .." and as a mention). I think some users might find it easier if the leading mention would be omitted (through a setting to hide the leading mention).

### Screenshots

![](https://user-images.githubusercontent.com/19953266/193679249-432b2562-b360-43ea-9223-aeec27443f67.png)

### OS and Chatterino Version

Chatterino Nightly 7.3.5 DEBUG (commit 1af89041 modified) built on 2022-09-27 with Qt 5.15.2, Windows SDK, MSVC 192428314

**Comment by pajlada** [comment]
What would be the default value for this setting?

What happens to the highlights that normally happen to you for every message in a thread you started?
  If highlights are not there anymore, is that a bad or unexpected thing?

**Comment by Felanbird** [comment]
> What would be the default value for this setting?

It very likely should be enabled. In browser chat there is absolutely no form of pinging due to replies and they are able to use replies perfectly fine, and I believe we could replicate that pattern in Chatterino as well. There is also a stigma due to the current way replies function, which makes people on stable 2.3.5 see users as replying to themselves, despite making perfect sense in a thread.
![image](https://user-images.githubusercontent.com/41973452/193693802-90f7cfc8-814b-4bb9-9ac5-5e1a43fe94e1.png)

> What happens to the highlights that normally happen to you for every message in a thread you started? If highlights are not there anymore, is that a bad or unexpected thing?

I don't think it's technically bad or unexpected due to the way it works in browser chat, it might cause minor confusion for users currently on post-reply nightly builds, but it likely ends up working out better that you aren't pinged by every reply in a thread, just because you hold the head message. Threads sometimes continue with a conversation between 2 unrelated people.

**Comment by Mm2PL** [comment]
4 paź 2022 00:09:12 Felanbird ***@***.***>:

> It very likely should be enabled.
I agree that replies shouldn't ping but completly hiding this mention text is just confusing, asking understanding of text being hidden automatically seems a little too much for the standard twitch pepega. Maybe the reply mention should somehow be grayed out or integrated into the "Replying to" header. 🤔

**Comment by Nerixyz** [comment]
Twitch chat removes the leading display name from the message:

```js
function f(e, n, t) {
  return void 0 === t && (t = {
  }),
  0 === e.indexOf('@'.concat(n, ' ')) ? {
    message: e.replace('@'.concat(n, ' '), ''),
    emotes: m(n, t)
  }
   : {
    message: e,
    emotes: t
  }
}
// equiv.
function strip(message, displayName, emotes) {
  if(emotes === undefined) emotes = {};
  
  const mention = '@'.concat(displayName, ' ');
  if (message.indexOf(mention) === 0) {
    return {
      message: message.replace(mention, ''),
      emotes: adjustEmoteIndices(displayName, emotes),
    };
  } else {
    return { message, emotes };
  }
}
```

![firefox_2022-10-04_12-14-32](https://user-images.githubusercontent.com/19953266/193794430-f1025f9c-45d9-4291-a9cb-f3db69412f09.png)

**Comment by Nerixyz** [comment]
I made the same modifications as on twitch. I think it's reasonable to hide the name, because it will always be the name of the user creating the initial thread, who is displayed above the message anyways:

![](https://user-images.githubusercontent.com/19953266/193804048-1d469625-5249-480c-98b0-432385c6d704.png)
![](https://user-images.githubusercontent.com/19953266/193804142-8fd2fb24-d644-4b71-a0bc-e0576c665654.png)

**Comment by dnsge** [comment]
Related discussion/commits:
https://github.com/Chatterino/chatterino2/pull/3722#discussion_r870603236
306f7a7194bd354727f41549f5ed1a8912d45097

**Comment by Felanbird** [comment]
> Related discussion/commits: [#3722 (comment)](https://github.com/Chatterino/chatterino2/pull/3722#discussion_r870603236) 

I never saw this comment but I disagree with it's logic. It just happened to align that @'s were ever shown in Chatterino, and based on the way they work in Twitch chat, they know that having @'s does not make sense, and they didn't implement the feature to properly use them.
The "not being lied to" argument is reasonable, but it generates a worse user experience, not better.

> but completely hiding this mention text is just confusing,

Why tho? If anything it would only cause confusion because of the way we originally implemented them, if we did this beforehand it would have made perfect sense, meaning the confusion would only apply to a small amount of nightly users, current stable users just see a normal @ and don't know the context unless told.

While I may have picked one specific person who dislikes the implementation, he has this dislike purely because of how often he's asked "why are you replying to yourself" from Chatterino users, when he is just trying to use the feature in browser chat.

**Comment by Felanbird** [comment]
The following changes were added:

We have gone ahead and removed the default leading `@mention` from reminders client side for the user. 
![image](https://user-images.githubusercontent.com/41973452/194712601-f23569df-4149-40ff-b9d0-7b2fc2a13436.png)
If you were a nightly user and you want to keep this functionality, you can disable the setting `Strip leading mention in replies`
![image](https://user-images.githubusercontent.com/41973452/194712666-3200bfc8-5efd-41bb-b809-7c00f5afd408.png)

We have also added a Highlight for `Participated Reply Threads` to makeup for the lack of pings. 
If a user replies to your thread, or replies are sent in a thread you replied to, the messages will be highlighted.
![image](https://user-images.githubusercontent.com/41973452/194713013-a193219f-e26c-4b8e-b793-fffcb6c5066f.png)
![image](https://user-images.githubusercontent.com/41973452/194713028-b084a0b7-58bf-458c-b3a3-342c0c32a7fc.png)
