### ISSUE TITLE
"Open in streamlink" does not work with streamlink 6.0.0

### ISSUE THREAD

**Issue by 3ship** [Chatterino/chatterino2#4730]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Streams cannot be opened via `streamlink` version 6.0.0. Reverting back to `streamlink` 5.5.1 resolves the issue.

Probably because in version 6.0.0 the `--player` (`-p`) flag now only accepts the player path.

Custom player arguments now always need to be set via `--player-args` (`-a`).

[Streamlink 6.0.0 release notes](https://github.com/streamlink/streamlink/releases/tag/6.0.0)

Terminal output:
```
[cli][info] Opening stream: 1080p60 (hls)
[cli][info] Starting player: mpv --cache 2048
[plugins.twitch][info] Will skip ad segments
error: Failed to start player: mpv --cache 2048 (Player executable not found)
[cli][info] Closing currently open stream...
```

### OS and Chatterino Version

Chatterino Nightly 2.4.4 (commit 7fd01ac57 modified) built on 2023-07-19 with Qt 5.15.8 Running on KDE Flatpak runtime, kernel: 6.1.39-1-lts, running from Flatpak

**Comment by Mm2PL** [comment]
This is a configuration issue created by streamlink 6.0.  As such this is not a Chatterino issue. We do not provide settings which set the player path. Instead of setting `--player "mpv --cache 2048"` consider using `--player mpv --player-args "--cache 2048"`. You also should check your streamlinkrc for this setting if its not present in Chatterino streamlink settings.
