### ISSUE TITLE
non-URI characters should be excluded from the link parser

### ISSUE THREAD

**Issue by brian6932** [Chatterino/chatterino2#4769]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Currently when you use a valid tld, the link parser doesn't check whether the domain characters are valid or not.

There are really 2 approaches you could go with this, you can either URI encode the characters within the white-space, imo that's unnatural and doesn't feel right for a chat program. The better thing to do is just exclude them like webchat does.

### Screenshots

c2:
![image](https://github.com/Chatterino/chatterino2/assets/18603393/90610092-8a2d-4a3b-b955-195bcb045452)
![image](https://github.com/Chatterino/chatterino2/assets/18603393/bcb4b571-0fa6-465d-b255-1fdaa027015a)
webchat:
![image](https://github.com/Chatterino/chatterino2/assets/18603393/0c29e2ac-ef67-4602-be10-4817a2e48857)

### OS and Chatterino Version

Chatterino Nightly 2.4.4 (commit 381d5c42) built on 2023-08-14 with Qt 5.15.2, MSVC 193532217 Running on Windows 10 Version 2009, kernel: 10.0.22621

**Comment by cbclemmer** [comment]
Added a PR to help with this #4778

**Comment by Felanbird** [comment]
I would prefer if the approach to fix this tackled the most user-facing problems, compared to patching tiny situations where a non-existent link is shown. Though this would likely require more of a refactor as it would result in two message elements.

Similar to the above mentioned `()` problem, links that trail with `.` are a more common user-facing problem. When this happens it's often due to a user writing a bot command, and ending the sentence with a `.`, which browser chat will ignore but Chatterino does not. In this case unless the link host handles this, the link will fail to load.

examples that automatically handle this problem:
[youtube](https://www.youtube.com/watch?v=lk-Br9AVVXU.)

examples where the link fails to load
[github](https://github.com/pajlada.)
[twitch](https://www.twitch.tv/pajlada.)
[runelite's plugin-hub](https://runelite.net/plugin-hub/show/dink.)
[dashduck's website](https://drscovy.com/raids.) | working version https://drscovy.com/raids

**Comment by Nerixyz** [comment]
I think parsing a link like this should work:

```
prefix                   link                          suffix
╭┴╮╭───────────────────────┴───────────────────────────╮╭┴─╮
 (  https://  foo.bar.baz.app  /my/path?query=alien#abc  ).
   ╰───┬────╯╰──────┬────────╯╰───────────┬────────────╯ 
    protocol      host                  rest
```
This could be stored in a result like this[^1]:
```cpp
struct Link {
    QStringView prefix;
    QStringView link;
    QStringView suffix;

    QStringView protocol;
    QStringView host;
    QStringView rest;

    QString source;
};
```

If `prefix` isn't empty, a text element is added for that. Then the link is added and finally the `suffix`. This way, the link would be properly highlighted.

The possible prefixes should be `(`. The possible suffixes should be `)`, `.`, `,`, `).` `),`.

[^1]: 🤓 On Qt 5.12 the string-views would be refs, because string-view support there is less than minimal (or lock link parsing to Qt 5.15 and up, so people switch to these versions and support for 5.12 can be dropped).
