### ISSUE TITLE
Incorrectly reporting as "Connected" to channels

### ISSUE THREAD

**Issue by Infinitay** [Chatterino/chatterino2#5066]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I've noticed that when launching C2 some channels fails to connect despite reporting as "Connected". Messages won't get read, there's no live indicator, and live notifications won't get sent. Furthermore, it doesn't see to resolve itself on its own unless I reopen the tab, but I haven't tested a reconnect (`CTRL+ F5`). I have reason to believe it happens (frequently) due to lots of tab being open or polling the data frequently. I haven't tested it for certain though.

### Screenshots

![image](https://github.com/Chatterino/chatterino2/assets/6964154/c0906c67-f9b3-4cb1-ae86-52dfb828dd93)

### OS and Chatterino Version

Chatterino Nightly + Dankerino patches 2.4.5 (commit 6fcc9b8e; based on 337b043b modified) built on 2023-10-02 with Qt 5.15.2, MSVC 193532217 Running on Windows 10 Version 2009, kernel: 10.0.19045

**Comment by pajlada** [comment]
`connected` implies you've connected to Twitch's chat servers
`joined channel` is what shows up when you've finally joined the specific Twitch channel

**Comment by Infinitay** [comment]
That makes sense. Despite seeing both connected and joined on some channels, I never made the distinction between the two states. I assumed connected and joined both implied the same thing with regards to the chat.

> `joined channel` is what shows up when you've finally joined the specific Twitch channel

Do we not have a retry attempt if the join fails upon connecting?

**Comment by pajlada** [comment]
> Do we not have a retry attempt if the join fails upon connecting?
iirc this was not trivial to achieve since it's not a request we make that gets a direct response, rather we need to do some guessery

We count receiving a `JOIN` for our own user as a success
We count receiving a notice with you being banned as a "Failed to join because you're banned"

We could technically implement some sort of timeout for it on our end, but it would be difficult to get right, and I don't see very much value in it especially since this is the first time I've ever heard of this happening.

The only thing I can consider happening for you is some sort of block or rate limiting, or the stars are misaligned for you

**Comment by Infinitay** [comment]
Seeing as C2 limits the amount of channels a user joins to prevent ratelimits, I suppose I'm having another issue due to something else on my end. Thanks for the info, but I'll go ahead and close this since I'm the only one having the issue at this time and it's probably a local issue.
