### ISSUE TITLE
IPC files on Windows can get large, and are not deleted

### ISSUE THREAD

**Issue by pajlada** [Chatterino/chatterino2#5227]
Full context available in https://github.com/Chatterino/chatterino2/issues/4084

The IPC files we create should be deleted on boot/shutdown

**Comment by 8thony** [comment]
Old
The file chatterino_gui is stored in `C:\ProgramData\boost_interprocess\<subfolder>\chatterino_gui`
The subfolder change from time to time (don't know a pattern) so the file is left there.

New since (449c539)
The file is stored in a defined folder inside appdata or same folder as the app, and it doesn't create any subfolder.
After you close c2 the only file left is 1 file with 103kb file size. Next time you start c2 this file gets overwritten.

In my opinion, it's fine, and this issues can be closed.
