### ISSUE TITLE
Emote completion with colon

### ISSUE THREAD

**Issue by Spaenny** [Chatterino/chatterino2#591]
It would be neat to have emote completion with colon like FFZ does currently, maybe make it an option to choose between colon and none for emote completion?

**Comment by infowolfe** [comment]
The current tab completion mechanism for emotes is extremely awkward and doesn't follow twitch "feel" from a ux perspective. Additionally, the tab-complete only seems to work from the start instead of twitch's greedy/lazy completion. if i type :pls it should offer up all `/(.*)pls(.*)/gxi` emotes via popup similar to the twitch UI/UX. Additionally, the current emotes popup/subwindow doesn't have any search/filtering capability, which makes it extremely difficult to quickly find emotes when you've got many channels subscribed.

**Comment by karl-police** [comment]
Not only emote, but also mention function

**Comment by apa420** [comment]
The point of doing : is to specify you want emotes and not usernames.

**Comment by karl-police** [comment]
> The point of doing : is to specify you want emotes and not usernames.

Obviously, I ment that when you do @ the popup appears. I was just talking about the Popup or the list.

**Comment by Ceono** [comment]
Still not a thing?

**Comment by Mm2PL** [comment]
This functionality hasn't been implemented yet, so it is still not a thing.

**Comment by apa420** [comment]
This is a open source project, feel free to implement it yourself! ;) @Ceono

**Comment by MastaNub** [comment]
Is this not gonna get added?

**Comment by karl-police** [comment]
> Is this not gonna get added?

Devs are busy probably, which is okay you know. Maybe it should be put on a to-do flair so it this doesn't get asked anymore.

**Comment by Thehail** [comment]
Waiting for this to be added, good suggestion.

**Comment by fourtf** [comment]
fixed in here https://github.com/Chatterino/chatterino2/commit/f7237dccdd5a4994b057967c3b3cdd7fa5166d55

twitch emotes and emojis will probably be added in a bit
