### ISSUE TITLE
Browser Extension doesn't work

### ISSUE THREAD

**Issue by notheowner** [Chatterino/chatterino2#745]
I haven't found an issue related to this yet. Browser Extension hasn't been working with the latest nightly builds for quite some time.
![2018-10-01_14-49-26](https://user-images.githubusercontent.com/25968992/46292589-3aa6c700-c589-11e8-878b-df5143c57550.png)

Works in latest beta build: 2.0.4

System: Windows 10, Chrome v69

**Comment by Defman21** [comment]
Does not work in Firefox too. Chatterino 2.0.4 (9472283-1).

**Comment by apa420** [comment]
I've looked into it and it would seem like the extension can't connect to chatterino with `chrome.runtime.connectNative` or similar to the firefox version.

The register is pointing to
`%appdata%/chatterino/native-messaging-manifest.json`
instead of
`%appdata%\Chatterino2\Misc\native-messaging-manifest-chrome.json`
(for chrome)

https://github.com/fourtf/chatterino2/blob/master/src/singletons/NativeMessaging.cpp#L47
Does not give the desired url to the desired application (in my case, I had my D:/ drive removed and was running chatterino from my C:/ drive and it was still pointing at the D:/ drive)
I assume this issue has to do with no proper updating support on where stuff is.

**Comment by Blomqen** [comment]
This is what comes out in the extension logs.

> Unchecked runtime.lastError: Specified native messaging host not found.

**Comment by fourtf** [comment]
Fixed
