### ISSUE TITLE
Feature: Inline Images

### ISSUE THREAD

**Issue by gempir** [Chatterino/chatterino2#792]
A cool feature for users could be the display of Inline-Images or preview images of websites. Programs like Slack or Discord would be great examples for this.

This should definitely optional and not turned on by default. This should also be proxied through a hosted service to avoid leaking of IPs. Although I still would like an option to turn off the proxy (with a Warning maybe, in case the Proxy breaks in the coming years)

**Comment by fourtf** [comment]
So you are telling me that you want to see all the images that twitch chat posts inline?

**Comment by gempir** [comment]
Yes. I want the option. Well maybe there should be a user/channel blacklist idk. I don't need one though.

**Comment by ThePridestalker** [comment]
api-cache from pajlada only needs to add the image on hover and you already have that

**Comment by ThePridestalker** [comment]
But inline images in a chat that goes fast would make it go even faster because of the height of the picture. It would be like those massive large emojis or big emote spams. Also since you can post more than 1 link in a message, the rest of messages would completely disappear by displaying all the links images. Not saying it wouldnt be useful for slow chats where people actually talk, but for more active chats it would be annoying from a 3rd POV where you see people posting pictures links and in your screen gets displayed, scrolling up all the messages. Not counting with the possibility of undesirable pictures.

**Comment by gempir** [comment]
So the option should probably channel specific. Also only the first image should be shown and it should be rendered after the text of the message

**Comment by hemirt** [comment]
It's probably only something for small communities, niche chats, proxying would be fine, but through what? it's probably going to be left to the users to set up their own proxy, as chatterino isnt an app with 130 million unique users and monetization options to support that, then it plumets from the few % of users who might use it, down to just a few individuals

**Comment by gempir** [comment]
The Link proxy is hosted by pajlada aswell so why not this aswell? I would offer hosting aswell.

**Comment by azizLIGHT** [comment]
Maybe it could be toggled per chat line like how some browser-based irc clients do it. 
Here's an example:
![record](https://user-images.githubusercontent.com/8013867/54509935-c1761300-4921-11e9-8556-eba556f748f9.gif)

**Comment by Mm2PL** [comment]
We already have the images on hover, this could be implemented really easily by reusing that.

**Comment by gempir** [comment]
Personally I don't want this feature anymore. The hover is sufficient for me.

If someone else still wants this please comment on this issue otherwise I'll close this.
