### ISSUE TITLE
Halloween ffz combo emotes don't show properly

### ISSUE THREAD

**Issue by apa420** [Chatterino/chatterino2#840]
![](https://i.nuuls.com/QxLDa.png)
left chatterino, right normal chat with ffz + ffz:ap

**Comment by TETYYS** [comment]
The way these FFZ combo emotes are implemented in webchat is awful, why did they think that applying a padding/margin to hardcoded emote IDs is good idea? It's in https://github.com/FrankerFaceZ/FrankerFaceZ/blob/master/src/modules/chat/emotes.js#L16 and I don't think it's a good idea to implement this in chatterino because these can be changed at any moment or moved to any other file, etc.

**Comment by pajlada** [comment]
The margins are also specified in the API we already poll, so it's not impossible
https://api.frankerfacez.com/v1/set/global
Since the event is over, I'm not 100% sure of the format but I think it's similar to the link you posted @TETYYS 
However - this most likely won't be implemented until maybe christmas when they have similar emotes with offsets

**Comment by Evanito** [comment]
Relevant due to event starting again

**Comment by apa420** [comment]
Incorrect, this issue is for ffz emotes, the christmas emotes are bttv.
Create another issue for bttv.

**Comment by apa420** [comment]
The emotes are gone, we'll make a new issue.
