### ISSUE TITLE
Losing mod privileges doesn't remove (hide) moderation buttons

### ISSUE THREAD

**Issue by CommName** [Chatterino/chatterino2#847]
When you unmod yourself you can still see moderation buttons.

**Comment by fourtf** [comment]
This is due to twitch not sending mod and unmod events properly (in irc)

**Comment by fourtf** [comment]
Maybe there's a proper pubsub event? @pajlada

**Comment by pajlada** [comment]
Not any documented one that I know of, no.
Only ways I know of doing this would be:
 a) automatically call .mods every now and then (which sucks)
 b) inspect any message that comes in that's from you (which would mean the moderation button only showing up if you type something in chat after being unmodded)
 c) potentially do b) and also listen to error NOTICE/USERNOTICE messages that happen if you try to timeout someone but the timeout fails because you're not a mod?

the +o/-o MODE messages are really unreliable

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
