### ISSUE TITLE
Multiple hosting messages after internet outage

### ISSUE THREAD

**Issue by apa420** [Chatterino/chatterino2#859]
![](https://i.nuuls.com/Im8M_.png)
Happened to me today, my router lost internet connection and I had to restart the router and didn't have internet for 5 min

![](https://i.nuuls.com/73w9p.png)
This time it didn't leak as it used to in #566 

Only messages that are "Now hosting x" is duplicating

**Comment by RAnders00** [comment]
this happens if you send a `JOIN #channelname` IRC command multiple times over the same conn, they probably get queued up somewhere and spammed when the connection succeeds

notice the double `NOTICE` command received:

![accbde00d7aa91ab](https://user-images.githubusercontent.com/1629196/57473456-2732ab80-7290-11e9-9101-a416c82d0b79.png)

**Comment by fourtf** [comment]
does this still happen?

**Comment by zneix** [comment]
I don't think this is a thing anymore, never saw this occur myself. If it does, please re-open
