### ISSUE TITLE
Emote menu is missing emotes in nightly when freshly opened for any channel.

### ISSUE THREAD

**Issue by gapbl4** [Chatterino/chatterino2#862]
Scrolling fixes the issue as you can see
![](https://i.imgur.com/WePR8We.gif)

Half of the time it looks like this
![](https://i.imgur.com/TrpTrqW.gif)

**Comment by Ckath** [comment]
looked into this a bit because I could reproduce on latest compiled from master(57069c6), it seems to work be an issue after 5453c65, compiling the from the commit before it results int he emote menu working normally. 

will try to look into it and throw a pr if I find a fix but thought i'd just leave this here if anyone else decides to look at it

**Comment by apa420** [comment]
Does this issue still occur?

**Comment by Ckath** [comment]
probably

**Comment by apa420** [comment]
What kind of answer is that

**Comment by gapbl4** [comment]
Doesn't seem like it's still happening. I already forgot about that issue, so I guess it can be closed.
