### ISSUE TITLE
/mentions & /whispers broken on startup (nightly)

### ISSUE THREAD

**Issue by JAYR4GE** [Chatterino/chatterino2#913]
If i have /whispers and /mentions open on startup it shows nothing - have to close and reopen it to show anything

nightly v1.0.863

**Comment by apa420** [comment]
I'm not really sure what your issue is, do you think you could have a video or something, or explain step by step what you do

**Comment by hemirt** [comment]
if you mean you need to reopen those, before they start working, then I can't replicate issue, they work for me right from start, otherwise

if you mean this:
if you close it with any mentions or whispers inside and reopen it, they stay there for me

if you mean to show old whispers/old mentions then:
/whispers would be weird to implement (how long old whispers would you want there? from which users?)
/mentions probably should show the mentions from the loaded recent messages

**Comment by JAYR4GE** [comment]
Just to let you know - downloaded the latest nightly and its working now as it should be

**Comment by RAnders00** [comment]
@fourtf close this?
