### ISSUE TITLE
Add support for messages other than PRIVMSG in recent messages

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#982]
https://github.com/fourtf/chatterino2/blob/3f41dfeff942d9becb311a4b1769e8445da016af/src/providers/twitch/TwitchChannel.cpp#L46

A potential recent_messages replacement could include other types of messages including CLEARCHAT, CLEARMSG, NOTICE and USERNOTICE.

Chatterino2 currently crashes when it encounters a non-PRIVMSG message.

**Comment by hemirt** [comment]
A potential replacement could be an endpoint which stores all the irc messages raw, and would add a tag "historical" as the twitch api used to be (it only used to have privmsgs)

**Comment by pajlada** [comment]
that's exactly what RAnders endpoint does, however chatterino, when loading historical messages, only supports PRIVMSG's

**Comment by hemirt** [comment]
i dont think you need a value for it _historical=1_ just a tag being there is fine

**Comment by hemirt** [comment]
would love support for this kind of solution and being able to add their own servers into it (aka fetch messages from myserver.com/historics, etc, and an option for headers

**Comment by pajlada** [comment]
> would love support for this kind of solution and being able to add their own servers into it (aka fetch messages from myserver.com/historics, etc, and an option for headers

url could just be an environment variable with a sane default. should probably be the same for the other external API's we call (like the link resolver)

**Comment by pajlada** [comment]
> 
> 
> i dont think you need a value for it _historical=1_ just a tag being there is fine

I think he just kept it as `historical=1` instead of `historical` for backwards compatability with anything that previously read the twitch api, as that's how they packaged it iirc

**Comment by hemirt** [comment]
i remembered that they didnt use any value, might be wrong on that
but the reason i would want that is to have multiple sources working at the same time

**Comment by pajlada** [comment]
multiple websites providing recent messages?
so you'd, for example, want to have a map that's set up like this:
```c++
std::map<std::string, std::string> recentMessagesProviders = {
  {"hemirt", "https://hemirt.com/recent_messages/%1"},
  {"pajlada", "https://hemirt.com/recent_messages/%1"},
  {"asdasd", "https://pajlada.com/recent_messages/%1"},
};
```
? possibly modifiable through a setting or something?

**Comment by hemirt** [comment]
at the simplest, yes
option to make per channel, (if for example some website doesnt send 404 but just times out, so that you can catch it) and global ones (just try every opened channel)

obviously there are multiple ways to sort out:
1) duplicates (via some msg id)
2) how long to wait till every provider responds
3) sort them via timestamp

(2 and 3 can be solved with having a method to insert a message such as that message is after messages with less timestamp and before messages with more timestamp)

an option for ?stuff=stuff&andsuch too

and later option for headers

**Comment by pajlada** [comment]
I don't personally like complicating it that much on the client side. At that point, you could just make a proxy/router that just routes your request depending om the channel, and the channel availability on the various providers

**Comment by hemirt** [comment]
a simple way for a url GET request and option for X channel only, or all channels, seems fine to me and not complicated, (custom headers could be a later added advanced option)

**Comment by hemirt** [comment]
@RAnders00 any option to withdraw from randers logging scheme?

**Comment by RAnders00** [comment]
@hemirt It‘s definitely coming, alongside a regular privacy notice and a privacy statement. I can manually blacklist your channel in the meantime until the feature is available.

**Comment by hemirt** [comment]
I thought I made myself several times very clear that I do not want any your chat bots, logging, or otherwise idling in my channel and put online, yes I would like to blacklist my channel.
Thank you
Am unsure how you add the channels to it, but if you're keen on hosting sth similar to overrustlelogs (that any channel can be added there)(*), then having a option to opt out would be very appreciated.
Good luck with that.

(*) beware of ingress / eggress network and any fees that might be with it

**Comment by hemirt** [comment]
back to the issue, the message could be casted accordingly to the command it represents, (accessed with the command mem fn http://communi.github.io/doc/3.0/class_irc_message.html#a5b5bfb1b4f3fa2211c7d559f8ced5706 )

**Comment by hemirt** [comment]
And it would probably be better to get rid of the "historic" tag altogether and just make it in the app, I think

**Comment by pajlada** [comment]
Why get rid of historic tag? You mean we should already know it's a historic message from the fact that the message came from the recent messages api? Sounds fair to ne

**Comment by RAnders00** [comment]
This is the data I based the response on: https://github.com/CBenni/mt2/issues/56#issue-316564263, which shows `historical=1`. It's completely fair though to ignore the historical tag and set the tag based on the place the message was loaded from.

**Comment by hemirt** [comment]
i think it's fixed, @pajlada close
